-- 0005-organizations-fk-on-delete.sql
--
-- Forward migration (see run-migrations.ts; 0001 is frozen). Append-only and
-- idempotent.
--
-- DB-1: deleting an organization used to raise an *unhandled* foreign-key 500.
-- Every org PATCH writes an `app_audit_events` row tagged with the org id, and
-- that FK had no ON DELETE action (= NO ACTION = blocks), so a member-less,
-- previously-edited org could never be deleted without a raw 500. The DELETE
-- guards only check `app_organization_memberships`, never the audit/role/binding
-- references.
--
-- The fix has two halves; the route change (FK violation -> 409
-- `organization_in_use`, mirroring enterprise-apps) and this migration:
--
--   1. app_audit_events.organization_id -> ON DELETE SET NULL. Audit is a
--      historical record: when its org is removed the event row must SURVIVE
--      with a null tenant (the 0001 schema comment already documents this
--      intent). This makes the common case — an org with only audit history —
--      deletable instead of a 500.
--
--   2. Teach the 0004 append-only trigger to permit EXACTLY that SET NULL
--      tombstone. The trigger (B3) rejects every UPDATE/DELETE on
--      app_audit_events, which would otherwise turn the SET NULL cascade into a
--      `check_violation` and re-break org deletion. The narrow exception below
--      allows only an UPDATE that nulls organization_id with every other column
--      byte-identical — so audit history survives org removal while the
--      tamper-evidence guarantee on row CONTENT is fully preserved.
--
-- Every OTHER org reference (app_roles, app_user_roles, app_provider_organizations,
-- app_enterprise_applications, app_api_keys, app_oauth_clients) intentionally
-- keeps its default RESTRICT/NO ACTION behavior: an org that still owns those
-- is genuinely "in use", so the DELETE raises a FK violation that the route now
-- translates to a clean 409 instead of a 500. (app_groups already CASCADEs and
-- app_outbox already SET NULLs per 0001.)

-- 1. Permit the org-deletion tombstone in the append-only trigger.
create or replace function app_audit_events_block_mutation()
  returns trigger
  language plpgsql
as $$
begin
  -- Sanctioned retention deletes opt in via a transaction-local GUC. The
  -- `true` makes current_setting return NULL (not error) when it is unset.
  if tg_op = 'DELETE' and current_setting('app.audit_retention', true) = 'on' then
    return old;
  end if;
  -- DB-1: an org DELETE fires `update app_audit_events set organization_id = null`
  -- via the ON DELETE SET NULL cascade below. Permit ONLY that exact tombstone —
  -- organization_id non-null -> null with EVERY other column unchanged — so the
  -- historical row is preserved (just detached from the deleted tenant) without
  -- opening any path to mutate audit content.
  if tg_op = 'UPDATE'
     and old.organization_id is not null
     and new.organization_id is null
     and (to_jsonb(new) - 'organization_id') = (to_jsonb(old) - 'organization_id') then
    return new;
  end if;
  raise exception 'app_audit_events is append-only: % is not permitted', tg_op
    using errcode = 'check_violation',
          hint = 'Audit rows are immutable; aged rows are removed only by the retention job.';
end;
$$;

-- 2. Flip app_audit_events.organization_id to ON DELETE SET NULL. The 0001 FK is
-- inline/unnamed; find it by its target + column rather than guessing the
-- autogenerated name, drop it, and re-add with a stable name + the SET NULL rule.
do $$
declare
  cname text;
begin
  select con.conname into cname
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  where rel.relname = 'app_audit_events'
    and con.contype = 'f'
    and con.confrelid = 'app_organizations'::regclass
    and (
      select attname
      from pg_attribute
      where attrelid = con.conrelid and attnum = con.conkey[1]
    ) = 'organization_id';
  if cname is not null then
    execute format('alter table app_audit_events drop constraint %I', cname);
  end if;
end $$;

alter table app_audit_events
  add constraint app_audit_events_organization_id_fkey
  foreign key (organization_id) references app_organizations(id) on delete set null;
