/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminApiKeyCreated,
  AdminApiKeyDetail,
  AdminApiKeyList,
  AdminApiKeyRevoked,
  AdminApiKeyRotated,
  AdminError,
  CreateAdminApiKeyRequest,
  RateLimitedError,
  ReasonRequest,
  UnprocessableError,
} from '../models/index';
import {
    AdminApiKeyCreatedFromJSON,
    AdminApiKeyCreatedToJSON,
    AdminApiKeyDetailFromJSON,
    AdminApiKeyDetailToJSON,
    AdminApiKeyListFromJSON,
    AdminApiKeyListToJSON,
    AdminApiKeyRevokedFromJSON,
    AdminApiKeyRevokedToJSON,
    AdminApiKeyRotatedFromJSON,
    AdminApiKeyRotatedToJSON,
    AdminErrorFromJSON,
    AdminErrorToJSON,
    CreateAdminApiKeyRequestFromJSON,
    CreateAdminApiKeyRequestToJSON,
    RateLimitedErrorFromJSON,
    RateLimitedErrorToJSON,
    ReasonRequestFromJSON,
    ReasonRequestToJSON,
    UnprocessableErrorFromJSON,
    UnprocessableErrorToJSON,
} from '../models/index';

export interface CreateAdminApiKeyOperationRequest {
    createAdminApiKeyRequest: CreateAdminApiKeyRequest;
}

export interface GetAdminApiKeyRequest {
    id: string;
}

export interface ListAdminApiKeysRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
    filterAppUserId?: Array<string>;
    filterOrganizationId?: Array<string>;
}

export interface RevokeAdminApiKeyRequest {
    id: string;
    reasonRequest?: ReasonRequest;
}

export interface RotateAdminApiKeyRequest {
    id: string;
}

/**
 * 
 */
export class APIKeysApi extends runtime.BaseAPI {

    /**
     * Issue an API key on behalf of a user (secret returned once)
     */
    async createAdminApiKeyRaw(requestParameters: CreateAdminApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminApiKeyCreated>> {
        if (requestParameters['createAdminApiKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createAdminApiKeyRequest',
                'Required parameter "createAdminApiKeyRequest" was null or undefined when calling createAdminApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAdminApiKeyRequestToJSON(requestParameters['createAdminApiKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminApiKeyCreatedFromJSON(jsonValue));
    }

    /**
     * Issue an API key on behalf of a user (secret returned once)
     */
    async createAdminApiKey(requestParameters: CreateAdminApiKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminApiKeyCreated> {
        const response = await this.createAdminApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read an API key\'s metadata
     */
    async getAdminApiKeyRaw(requestParameters: GetAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminApiKeyDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAdminApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminApiKeyDetailFromJSON(jsonValue));
    }

    /**
     * Read an API key\'s metadata
     */
    async getAdminApiKey(requestParameters: GetAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminApiKeyDetail> {
        const response = await this.getAdminApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List API keys (governance)
     */
    async listAdminApiKeysRaw(requestParameters: ListAdminApiKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminApiKeyList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterAppUserId'] != null) {
            queryParameters['filter[app_user_id]'] = requestParameters['filterAppUserId'];
        }

        if (requestParameters['filterOrganizationId'] != null) {
            queryParameters['filter[organization_id]'] = requestParameters['filterOrganizationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminApiKeyListFromJSON(jsonValue));
    }

    /**
     * List API keys (governance)
     */
    async listAdminApiKeys(requestParameters: ListAdminApiKeysRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminApiKeyList> {
        const response = await this.listAdminApiKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke an API key
     */
    async revokeAdminApiKeyRaw(requestParameters: RevokeAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminApiKeyRevoked>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeAdminApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ReasonRequestToJSON(requestParameters['reasonRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminApiKeyRevokedFromJSON(jsonValue));
    }

    /**
     * Revoke an API key
     */
    async revokeAdminApiKey(requestParameters: RevokeAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminApiKeyRevoked> {
        const response = await this.revokeAdminApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate an API key (new secret returned once)
     */
    async rotateAdminApiKeyRaw(requestParameters: RotateAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminApiKeyRotated>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rotateAdminApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api-keys/{id}/rotate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminApiKeyRotatedFromJSON(jsonValue));
    }

    /**
     * Rotate an API key (new secret returned once)
     */
    async rotateAdminApiKey(requestParameters: RotateAdminApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminApiKeyRotated> {
        const response = await this.rotateAdminApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
