/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminError,
  AuditEventList,
} from '../models/index';
import {
    AdminErrorFromJSON,
    AdminErrorToJSON,
    AuditEventListFromJSON,
    AuditEventListToJSON,
} from '../models/index';

export interface ListAuditEventsRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterEventType?: Array<string>;
    filterOutcome?: Array<string>;
    filterActor?: Array<string>;
    filterAppUserId?: Array<string>;
    filterOrganizationId?: Array<string>;
    filterTargetApplicationId?: Array<string>;
}

/**
 * 
 */
export class AuditApi extends runtime.BaseAPI {

    /**
     * Read the audit log
     */
    async listAuditEventsRaw(requestParameters: ListAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuditEventList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterEventType'] != null) {
            queryParameters['filter[event_type]'] = requestParameters['filterEventType'];
        }

        if (requestParameters['filterOutcome'] != null) {
            queryParameters['filter[outcome]'] = requestParameters['filterOutcome'];
        }

        if (requestParameters['filterActor'] != null) {
            queryParameters['filter[actor]'] = requestParameters['filterActor'];
        }

        if (requestParameters['filterAppUserId'] != null) {
            queryParameters['filter[app_user_id]'] = requestParameters['filterAppUserId'];
        }

        if (requestParameters['filterOrganizationId'] != null) {
            queryParameters['filter[organization_id]'] = requestParameters['filterOrganizationId'];
        }

        if (requestParameters['filterTargetApplicationId'] != null) {
            queryParameters['filter[target_application_id]'] = requestParameters['filterTargetApplicationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/audit`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuditEventListFromJSON(jsonValue));
    }

    /**
     * Read the audit log
     */
    async listAuditEvents(requestParameters: ListAuditEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuditEventList> {
        const response = await this.listAuditEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
