/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminError,
  EmailTemplate,
  EmailTemplateListEnvelope,
  OkId,
  OutboxDetail,
  OutboxList,
  RateLimitedError,
  SendTestEmailRequest,
  SendTestEmailResult,
  UpdateEmailTemplateRequest,
} from '../models/index';
import {
    AdminErrorFromJSON,
    AdminErrorToJSON,
    EmailTemplateFromJSON,
    EmailTemplateToJSON,
    EmailTemplateListEnvelopeFromJSON,
    EmailTemplateListEnvelopeToJSON,
    OkIdFromJSON,
    OkIdToJSON,
    OutboxDetailFromJSON,
    OutboxDetailToJSON,
    OutboxListFromJSON,
    OutboxListToJSON,
    RateLimitedErrorFromJSON,
    RateLimitedErrorToJSON,
    SendTestEmailRequestFromJSON,
    SendTestEmailRequestToJSON,
    SendTestEmailResultFromJSON,
    SendTestEmailResultToJSON,
    UpdateEmailTemplateRequestFromJSON,
    UpdateEmailTemplateRequestToJSON,
} from '../models/index';

export interface GetEmailTemplateRequest {
    id: string;
}

export interface GetOutboxItemRequest {
    id: string;
}

export interface ListOutboxRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
    filterTemplateKey?: Array<string>;
}

export interface SendTestEmailOperationRequest {
    sendTestEmailRequest: SendTestEmailRequest;
}

export interface UpdateEmailTemplateOperationRequest {
    id: string;
    updateEmailTemplateRequest: UpdateEmailTemplateRequest;
}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI {

    /**
     * Read an email template
     */
    async getEmailTemplateRaw(requestParameters: GetEmailTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailTemplate>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmailTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailTemplateFromJSON(jsonValue));
    }

    /**
     * Read an email template
     */
    async getEmailTemplate(requestParameters: GetEmailTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailTemplate> {
        const response = await this.getEmailTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read one outbox row with its (redacted) bodies
     */
    async getOutboxItemRaw(requestParameters: GetOutboxItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboxDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOutboxItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/outbox/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutboxDetailFromJSON(jsonValue));
    }

    /**
     * Read one outbox row with its (redacted) bodies
     */
    async getOutboxItem(requestParameters: GetOutboxItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboxDetail> {
        const response = await this.getOutboxItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List email templates
     */
    async listEmailTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailTemplateListEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/templates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailTemplateListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List email templates
     */
    async listEmailTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailTemplateListEnvelope> {
        const response = await this.listEmailTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * List the email outbox (metadata only)
     */
    async listOutboxRaw(requestParameters: ListOutboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboxList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterTemplateKey'] != null) {
            queryParameters['filter[template_key]'] = requestParameters['filterTemplateKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/outbox`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutboxListFromJSON(jsonValue));
    }

    /**
     * List the email outbox (metadata only)
     */
    async listOutbox(requestParameters: ListOutboxRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboxList> {
        const response = await this.listOutboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a test email
     */
    async sendTestEmailRaw(requestParameters: SendTestEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendTestEmailResult>> {
        if (requestParameters['sendTestEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'sendTestEmailRequest',
                'Required parameter "sendTestEmailRequest" was null or undefined when calling sendTestEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/test`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendTestEmailRequestToJSON(requestParameters['sendTestEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendTestEmailResultFromJSON(jsonValue));
    }

    /**
     * Send a test email
     */
    async sendTestEmail(requestParameters: SendTestEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendTestEmailResult> {
        const response = await this.sendTestEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an email template (superadmin only)
     */
    async updateEmailTemplateRaw(requestParameters: UpdateEmailTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkId>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmailTemplate().'
            );
        }

        if (requestParameters['updateEmailTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEmailTemplateRequest',
                'Required parameter "updateEmailTemplateRequest" was null or undefined when calling updateEmailTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/email/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmailTemplateRequestToJSON(requestParameters['updateEmailTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkIdFromJSON(jsonValue));
    }

    /**
     * Update an email template (superadmin only)
     */
    async updateEmailTemplate(requestParameters: UpdateEmailTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkId> {
        const response = await this.updateEmailTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
