/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminError,
  CreateEnterpriseAppRequest,
  EnterpriseAppDetail,
  EnterpriseAppList,
  IdCreated,
  Ok,
  RateLimitedError,
  UpdateEnterpriseAppRequest,
} from '../models/index';
import {
    AdminErrorFromJSON,
    AdminErrorToJSON,
    CreateEnterpriseAppRequestFromJSON,
    CreateEnterpriseAppRequestToJSON,
    EnterpriseAppDetailFromJSON,
    EnterpriseAppDetailToJSON,
    EnterpriseAppListFromJSON,
    EnterpriseAppListToJSON,
    IdCreatedFromJSON,
    IdCreatedToJSON,
    OkFromJSON,
    OkToJSON,
    RateLimitedErrorFromJSON,
    RateLimitedErrorToJSON,
    UpdateEnterpriseAppRequestFromJSON,
    UpdateEnterpriseAppRequestToJSON,
} from '../models/index';

export interface CreateEnterpriseAppOperationRequest {
    createEnterpriseAppRequest: CreateEnterpriseAppRequest;
}

export interface DeleteEnterpriseAppRequest {
    id: string;
}

export interface GetEnterpriseAppRequest {
    id: string;
}

export interface ListEnterpriseAppsRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
    filterOrganizationId?: Array<string>;
}

export interface UpdateEnterpriseAppOperationRequest {
    id: string;
    updateEnterpriseAppRequest: UpdateEnterpriseAppRequest;
}

/**
 * 
 */
export class EnterpriseAppsApi extends runtime.BaseAPI {

    /**
     * Register an enterprise application
     */
    async createEnterpriseAppRaw(requestParameters: CreateEnterpriseAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IdCreated>> {
        if (requestParameters['createEnterpriseAppRequest'] == null) {
            throw new runtime.RequiredError(
                'createEnterpriseAppRequest',
                'Required parameter "createEnterpriseAppRequest" was null or undefined when calling createEnterpriseApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/enterprise-apps`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEnterpriseAppRequestToJSON(requestParameters['createEnterpriseAppRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdCreatedFromJSON(jsonValue));
    }

    /**
     * Register an enterprise application
     */
    async createEnterpriseApp(requestParameters: CreateEnterpriseAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IdCreated> {
        const response = await this.createEnterpriseAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an enterprise application
     */
    async deleteEnterpriseAppRaw(requestParameters: DeleteEnterpriseAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEnterpriseApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/enterprise-apps/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Delete an enterprise application
     */
    async deleteEnterpriseApp(requestParameters: DeleteEnterpriseAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.deleteEnterpriseAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read an enterprise application
     */
    async getEnterpriseAppRaw(requestParameters: GetEnterpriseAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnterpriseAppDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEnterpriseApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/enterprise-apps/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnterpriseAppDetailFromJSON(jsonValue));
    }

    /**
     * Read an enterprise application
     */
    async getEnterpriseApp(requestParameters: GetEnterpriseAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnterpriseAppDetail> {
        const response = await this.getEnterpriseAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List enterprise applications
     */
    async listEnterpriseAppsRaw(requestParameters: ListEnterpriseAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnterpriseAppList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterOrganizationId'] != null) {
            queryParameters['filter[organization_id]'] = requestParameters['filterOrganizationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/enterprise-apps`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnterpriseAppListFromJSON(jsonValue));
    }

    /**
     * List enterprise applications
     */
    async listEnterpriseApps(requestParameters: ListEnterpriseAppsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnterpriseAppList> {
        const response = await this.listEnterpriseAppsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an enterprise application
     */
    async updateEnterpriseAppRaw(requestParameters: UpdateEnterpriseAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEnterpriseApp().'
            );
        }

        if (requestParameters['updateEnterpriseAppRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEnterpriseAppRequest',
                'Required parameter "updateEnterpriseAppRequest" was null or undefined when calling updateEnterpriseApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/enterprise-apps/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEnterpriseAppRequestToJSON(requestParameters['updateEnterpriseAppRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Update an enterprise application
     */
    async updateEnterpriseApp(requestParameters: UpdateEnterpriseAppOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.updateEnterpriseAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
