/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminError,
  GlobalMembershipList,
} from '../models/index';
import {
    AdminErrorFromJSON,
    AdminErrorToJSON,
    GlobalMembershipListFromJSON,
    GlobalMembershipListToJSON,
} from '../models/index';

export interface ListMembershipsRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
    filterOrganizationId?: Array<string>;
    filterSourceProvider?: Array<string>;
}

/**
 * 
 */
export class MembershipsApi extends runtime.BaseAPI {

    /**
     * List all memberships (cross-org)
     */
    async listMembershipsRaw(requestParameters: ListMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlobalMembershipList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterOrganizationId'] != null) {
            queryParameters['filter[organization_id]'] = requestParameters['filterOrganizationId'];
        }

        if (requestParameters['filterSourceProvider'] != null) {
            queryParameters['filter[source_provider]'] = requestParameters['filterSourceProvider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/memberships`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalMembershipListFromJSON(jsonValue));
    }

    /**
     * List all memberships (cross-org)
     */
    async listMemberships(requestParameters: ListMembershipsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlobalMembershipList> {
        const response = await this.listMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
