/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddOrgMemberRequest,
  AddProviderBindingRequest,
  AdminError,
  AuthPolicyEnvelope,
  CreateInvitationRequest,
  CreateOrganizationRequest,
  DeleteBindingsRequest,
  DeleteMembershipsRequest,
  InvitationCreated,
  InvitationList,
  InvitationResent,
  KeyCreated,
  Ok,
  OkCount,
  OkId,
  OrgMemberList,
  OrganizationDetail,
  OrganizationList,
  ProviderBindingList,
  RateLimitedError,
  UpdateAuthPolicyRequest,
  UpdateMembershipsRequest,
  UpdateOrganizationRequest,
} from '../models/index';
import {
    AddOrgMemberRequestFromJSON,
    AddOrgMemberRequestToJSON,
    AddProviderBindingRequestFromJSON,
    AddProviderBindingRequestToJSON,
    AdminErrorFromJSON,
    AdminErrorToJSON,
    AuthPolicyEnvelopeFromJSON,
    AuthPolicyEnvelopeToJSON,
    CreateInvitationRequestFromJSON,
    CreateInvitationRequestToJSON,
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
    DeleteBindingsRequestFromJSON,
    DeleteBindingsRequestToJSON,
    DeleteMembershipsRequestFromJSON,
    DeleteMembershipsRequestToJSON,
    InvitationCreatedFromJSON,
    InvitationCreatedToJSON,
    InvitationListFromJSON,
    InvitationListToJSON,
    InvitationResentFromJSON,
    InvitationResentToJSON,
    KeyCreatedFromJSON,
    KeyCreatedToJSON,
    OkFromJSON,
    OkToJSON,
    OkCountFromJSON,
    OkCountToJSON,
    OkIdFromJSON,
    OkIdToJSON,
    OrgMemberListFromJSON,
    OrgMemberListToJSON,
    OrganizationDetailFromJSON,
    OrganizationDetailToJSON,
    OrganizationListFromJSON,
    OrganizationListToJSON,
    ProviderBindingListFromJSON,
    ProviderBindingListToJSON,
    RateLimitedErrorFromJSON,
    RateLimitedErrorToJSON,
    UpdateAuthPolicyRequestFromJSON,
    UpdateAuthPolicyRequestToJSON,
    UpdateMembershipsRequestFromJSON,
    UpdateMembershipsRequestToJSON,
    UpdateOrganizationRequestFromJSON,
    UpdateOrganizationRequestToJSON,
} from '../models/index';

export interface AddOrganizationMemberRequest {
    id: string;
    addOrgMemberRequest: AddOrgMemberRequest;
}

export interface AddProviderBindingOperationRequest {
    id: string;
    addProviderBindingRequest: AddProviderBindingRequest;
}

export interface CreateOrganizationOperationRequest {
    createOrganizationRequest: CreateOrganizationRequest;
}

export interface CreateOrganizationInvitationRequest {
    id: string;
    createInvitationRequest: CreateInvitationRequest;
}

export interface DeleteOrganizationRequest {
    id: string;
}

export interface GetOrganizationRequest {
    id: string;
}

export interface GetOrganizationAuthSettingsRequest {
    id: string;
}

export interface ListOrganizationInvitationsRequest {
    id: string;
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
}

export interface ListOrganizationMembersRequest {
    id: string;
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
}

export interface ListOrganizationsRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
    filterIsDefault?: Array<string>;
}

export interface ListProviderBindingsRequest {
    id: string;
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    filterProvider?: Array<string>;
}

export interface RemoveOrganizationMembersRequest {
    id: string;
    deleteMembershipsRequest: DeleteMembershipsRequest;
}

export interface RemoveProviderBindingsRequest {
    id: string;
    deleteBindingsRequest: DeleteBindingsRequest;
}

export interface ResendOrganizationInvitationRequest {
    id: string;
    invitationId: string;
}

export interface ResetOrganizationAuthSettingsRequest {
    id: string;
}

export interface RevokeOrganizationInvitationRequest {
    id: string;
    invitationId: string;
}

export interface UpdateOrganizationOperationRequest {
    id: string;
    updateOrganizationRequest: UpdateOrganizationRequest;
}

export interface UpdateOrganizationAuthSettingsRequest {
    id: string;
    updateAuthPolicyRequest: UpdateAuthPolicyRequest;
}

export interface UpdateOrganizationMembersRequest {
    id: string;
    updateMembershipsRequest: UpdateMembershipsRequest;
}

export interface UpdatePlatformAuthSettingsRequest {
    updateAuthPolicyRequest: UpdateAuthPolicyRequest;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Add a member to the organization
     */
    async addOrganizationMemberRaw(requestParameters: AddOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkId>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addOrganizationMember().'
            );
        }

        if (requestParameters['addOrgMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'addOrgMemberRequest',
                'Required parameter "addOrgMemberRequest" was null or undefined when calling addOrganizationMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/members`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddOrgMemberRequestToJSON(requestParameters['addOrgMemberRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkIdFromJSON(jsonValue));
    }

    /**
     * Add a member to the organization
     */
    async addOrganizationMember(requestParameters: AddOrganizationMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkId> {
        const response = await this.addOrganizationMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a provider binding
     */
    async addProviderBindingRaw(requestParameters: AddProviderBindingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkId>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addProviderBinding().'
            );
        }

        if (requestParameters['addProviderBindingRequest'] == null) {
            throw new runtime.RequiredError(
                'addProviderBindingRequest',
                'Required parameter "addProviderBindingRequest" was null or undefined when calling addProviderBinding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/provider-bindings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddProviderBindingRequestToJSON(requestParameters['addProviderBindingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkIdFromJSON(jsonValue));
    }

    /**
     * Add a provider binding
     */
    async addProviderBinding(requestParameters: AddProviderBindingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkId> {
        const response = await this.addProviderBindingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an organization (superadmin only)
     */
    async createOrganizationRaw(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyCreated>> {
        if (requestParameters['createOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationRequest',
                'Required parameter "createOrganizationRequest" was null or undefined when calling createOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyCreatedFromJSON(jsonValue));
    }

    /**
     * Create an organization (superadmin only)
     */
    async createOrganization(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyCreated> {
        const response = await this.createOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invite an email address into the organization (sends the accept link)
     */
    async createOrganizationInvitationRaw(requestParameters: CreateOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationCreated>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createOrganizationInvitation().'
            );
        }

        if (requestParameters['createInvitationRequest'] == null) {
            throw new runtime.RequiredError(
                'createInvitationRequest',
                'Required parameter "createInvitationRequest" was null or undefined when calling createOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/invitations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInvitationRequestToJSON(requestParameters['createInvitationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationCreatedFromJSON(jsonValue));
    }

    /**
     * Invite an email address into the organization (sends the accept link)
     */
    async createOrganizationInvitation(requestParameters: CreateOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationCreated> {
        const response = await this.createOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an organization (superadmin only)
     */
    async deleteOrganizationRaw(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Delete an organization (superadmin only)
     */
    async deleteOrganization(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.deleteOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read an organization
     */
    async getOrganizationRaw(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationDetailFromJSON(jsonValue));
    }

    /**
     * Read an organization
     */
    async getOrganization(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationDetail> {
        const response = await this.getOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read an organization\'s signup policy (raw override + effective resolution)
     */
    async getOrganizationAuthSettingsRaw(requestParameters: GetOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPolicyEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganizationAuthSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/auth-settings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPolicyEnvelopeFromJSON(jsonValue));
    }

    /**
     * Read an organization\'s signup policy (raw override + effective resolution)
     */
    async getOrganizationAuthSettings(requestParameters: GetOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPolicyEnvelope> {
        const response = await this.getOrganizationAuthSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read the platform-default signup policy (superadmin only)
     */
    async getPlatformAuthSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPolicyEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth-settings/defaults`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPolicyEnvelopeFromJSON(jsonValue));
    }

    /**
     * Read the platform-default signup policy (superadmin only)
     */
    async getPlatformAuthSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPolicyEnvelope> {
        const response = await this.getPlatformAuthSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List an organization\'s invitations
     */
    async listOrganizationInvitationsRaw(requestParameters: ListOrganizationInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listOrganizationInvitations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/invitations`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationListFromJSON(jsonValue));
    }

    /**
     * List an organization\'s invitations
     */
    async listOrganizationInvitations(requestParameters: ListOrganizationInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationList> {
        const response = await this.listOrganizationInvitationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List an organization\'s members
     */
    async listOrganizationMembersRaw(requestParameters: ListOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgMemberList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listOrganizationMembers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/members`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgMemberListFromJSON(jsonValue));
    }

    /**
     * List an organization\'s members
     */
    async listOrganizationMembers(requestParameters: ListOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgMemberList> {
        const response = await this.listOrganizationMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List organizations
     */
    async listOrganizationsRaw(requestParameters: ListOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterIsDefault'] != null) {
            queryParameters['filter[is_default]'] = requestParameters['filterIsDefault'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationListFromJSON(jsonValue));
    }

    /**
     * List organizations
     */
    async listOrganizations(requestParameters: ListOrganizationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationList> {
        const response = await this.listOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List an organization\'s provider bindings
     */
    async listProviderBindingsRaw(requestParameters: ListProviderBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderBindingList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listProviderBindings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['filterProvider'] != null) {
            queryParameters['filter[provider]'] = requestParameters['filterProvider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/provider-bindings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderBindingListFromJSON(jsonValue));
    }

    /**
     * List an organization\'s provider bindings
     */
    async listProviderBindings(requestParameters: ListProviderBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderBindingList> {
        const response = await this.listProviderBindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Bulk-remove members
     */
    async removeOrganizationMembersRaw(requestParameters: RemoveOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkCount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeOrganizationMembers().'
            );
        }

        if (requestParameters['deleteMembershipsRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteMembershipsRequest',
                'Required parameter "deleteMembershipsRequest" was null or undefined when calling removeOrganizationMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/members`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteMembershipsRequestToJSON(requestParameters['deleteMembershipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkCountFromJSON(jsonValue));
    }

    /**
     * Bulk-remove members
     */
    async removeOrganizationMembers(requestParameters: RemoveOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkCount> {
        const response = await this.removeOrganizationMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove provider bindings
     */
    async removeProviderBindingsRaw(requestParameters: RemoveProviderBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkCount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeProviderBindings().'
            );
        }

        if (requestParameters['deleteBindingsRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteBindingsRequest',
                'Required parameter "deleteBindingsRequest" was null or undefined when calling removeProviderBindings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/provider-bindings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteBindingsRequestToJSON(requestParameters['deleteBindingsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkCountFromJSON(jsonValue));
    }

    /**
     * Remove provider bindings
     */
    async removeProviderBindings(requestParameters: RemoveProviderBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkCount> {
        const response = await this.removeProviderBindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate a pending invitation\'s token + expiry and re-send the email
     */
    async resendOrganizationInvitationRaw(requestParameters: ResendOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationResent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resendOrganizationInvitation().'
            );
        }

        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling resendOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/invitations/{invitationId}/resend`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"invitationId"}}`, encodeURIComponent(String(requestParameters['invitationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationResentFromJSON(jsonValue));
    }

    /**
     * Rotate a pending invitation\'s token + expiry and re-send the email
     */
    async resendOrganizationInvitation(requestParameters: ResendOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationResent> {
        const response = await this.resendOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove the signup-policy override (revert to the platform default)
     */
    async resetOrganizationAuthSettingsRaw(requestParameters: ResetOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resetOrganizationAuthSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/auth-settings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Remove the signup-policy override (revert to the platform default)
     */
    async resetOrganizationAuthSettings(requestParameters: ResetOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.resetOrganizationAuthSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a pending invitation (the accept link dies immediately)
     */
    async revokeOrganizationInvitationRaw(requestParameters: RevokeOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeOrganizationInvitation().'
            );
        }

        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling revokeOrganizationInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/invitations/{invitationId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"invitationId"}}`, encodeURIComponent(String(requestParameters['invitationId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Revoke a pending invitation (the accept link dies immediately)
     */
    async revokeOrganizationInvitation(requestParameters: RevokeOrganizationInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.revokeOrganizationInvitationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an organization (superadmin only)
     */
    async updateOrganizationRaw(requestParameters: UpdateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOrganization().'
            );
        }

        if (requestParameters['updateOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationRequest',
                'Required parameter "updateOrganizationRequest" was null or undefined when calling updateOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationRequestToJSON(requestParameters['updateOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Update an organization (superadmin only)
     */
    async updateOrganization(requestParameters: UpdateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.updateOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or replace the organization\'s signup-policy override
     */
    async updateOrganizationAuthSettingsRaw(requestParameters: UpdateOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPolicyEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOrganizationAuthSettings().'
            );
        }

        if (requestParameters['updateAuthPolicyRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAuthPolicyRequest',
                'Required parameter "updateAuthPolicyRequest" was null or undefined when calling updateOrganizationAuthSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/auth-settings`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAuthPolicyRequestToJSON(requestParameters['updateAuthPolicyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPolicyEnvelopeFromJSON(jsonValue));
    }

    /**
     * Create or replace the organization\'s signup-policy override
     */
    async updateOrganizationAuthSettings(requestParameters: UpdateOrganizationAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPolicyEnvelope> {
        const response = await this.updateOrganizationAuthSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Bulk-update member statuses
     */
    async updateOrganizationMembersRaw(requestParameters: UpdateOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkCount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOrganizationMembers().'
            );
        }

        if (requestParameters['updateMembershipsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMembershipsRequest',
                'Required parameter "updateMembershipsRequest" was null or undefined when calling updateOrganizationMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organizations/{id}/members`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMembershipsRequestToJSON(requestParameters['updateMembershipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkCountFromJSON(jsonValue));
    }

    /**
     * Bulk-update member statuses
     */
    async updateOrganizationMembers(requestParameters: UpdateOrganizationMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkCount> {
        const response = await this.updateOrganizationMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the platform-default signup policy (superadmin only)
     */
    async updatePlatformAuthSettingsRaw(requestParameters: UpdatePlatformAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPolicyEnvelope>> {
        if (requestParameters['updateAuthPolicyRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAuthPolicyRequest',
                'Required parameter "updateAuthPolicyRequest" was null or undefined when calling updatePlatformAuthSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth-settings/defaults`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAuthPolicyRequestToJSON(requestParameters['updateAuthPolicyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPolicyEnvelopeFromJSON(jsonValue));
    }

    /**
     * Update the platform-default signup policy (superadmin only)
     */
    async updatePlatformAuthSettings(requestParameters: UpdatePlatformAuthSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPolicyEnvelope> {
        const response = await this.updatePlatformAuthSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
