/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddMembershipRequest,
  AdminError,
  AppRoleAssignments,
  AppRoleRef,
  BanRequest,
  BulkUserRequest,
  BulkUserResult,
  CreateUserRequest,
  DeleteMembershipsRequest,
  MembershipList,
  Ok,
  OkCount,
  OkId,
  OkStatus,
  ReasonRequest,
  SessionList,
  SetPasswordRequest,
  SetRoleRequest,
  SetUserPassword200Response,
  SetUserPlatformRole200Response,
  UpdateMembershipsRequest,
  UpdateUserRequest,
  UserCreated,
  UserDetailEnvelope,
  UserGroupRef,
  UserGroups,
  UserList,
  UserStatusRequest,
} from '../models/index';
import {
    AddMembershipRequestFromJSON,
    AddMembershipRequestToJSON,
    AdminErrorFromJSON,
    AdminErrorToJSON,
    AppRoleAssignmentsFromJSON,
    AppRoleAssignmentsToJSON,
    AppRoleRefFromJSON,
    AppRoleRefToJSON,
    BanRequestFromJSON,
    BanRequestToJSON,
    BulkUserRequestFromJSON,
    BulkUserRequestToJSON,
    BulkUserResultFromJSON,
    BulkUserResultToJSON,
    CreateUserRequestFromJSON,
    CreateUserRequestToJSON,
    DeleteMembershipsRequestFromJSON,
    DeleteMembershipsRequestToJSON,
    MembershipListFromJSON,
    MembershipListToJSON,
    OkFromJSON,
    OkToJSON,
    OkCountFromJSON,
    OkCountToJSON,
    OkIdFromJSON,
    OkIdToJSON,
    OkStatusFromJSON,
    OkStatusToJSON,
    ReasonRequestFromJSON,
    ReasonRequestToJSON,
    SessionListFromJSON,
    SessionListToJSON,
    SetPasswordRequestFromJSON,
    SetPasswordRequestToJSON,
    SetRoleRequestFromJSON,
    SetRoleRequestToJSON,
    SetUserPassword200ResponseFromJSON,
    SetUserPassword200ResponseToJSON,
    SetUserPlatformRole200ResponseFromJSON,
    SetUserPlatformRole200ResponseToJSON,
    UpdateMembershipsRequestFromJSON,
    UpdateMembershipsRequestToJSON,
    UpdateUserRequestFromJSON,
    UpdateUserRequestToJSON,
    UserCreatedFromJSON,
    UserCreatedToJSON,
    UserDetailEnvelopeFromJSON,
    UserDetailEnvelopeToJSON,
    UserGroupRefFromJSON,
    UserGroupRefToJSON,
    UserGroupsFromJSON,
    UserGroupsToJSON,
    UserListFromJSON,
    UserListToJSON,
    UserStatusRequestFromJSON,
    UserStatusRequestToJSON,
} from '../models/index';

export interface AddUserMembershipRequest {
    id: string;
    addMembershipRequest: AddMembershipRequest;
}

export interface AddUserToGroupRequest {
    id: string;
    userGroupRef: UserGroupRef;
}

export interface AssignUserAppRoleRequest {
    id: string;
    appRoleRef: AppRoleRef;
}

export interface BanUserRequest {
    id: string;
    banRequest: BanRequest;
}

export interface BulkUserActionRequest {
    bulkUserRequest: BulkUserRequest;
}

export interface CreateUserOperationRequest {
    createUserRequest: CreateUserRequest;
}

export interface DeleteUserRequest {
    id: string;
    reasonRequest?: ReasonRequest;
}

export interface GetUserRequest {
    id: string;
}

export interface ListUserAppRolesRequest {
    id: string;
}

export interface ListUserGroupsRequest {
    id: string;
}

export interface ListUserMembershipsRequest {
    id: string;
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    filterStatus?: Array<string>;
    filterOrganizationId?: Array<string>;
}

export interface ListUserSessionsRequest {
    id: string;
}

export interface ListUsersRequest {
    page?: number;
    pageSize?: number;
    sort?: Array<string>;
    q?: string;
    filterStatus?: Array<string>;
}

export interface RemoveUserFromGroupRequest {
    id: string;
    userGroupRef: UserGroupRef;
}

export interface RemoveUserMembershipsRequest {
    id: string;
    deleteMembershipsRequest: DeleteMembershipsRequest;
}

export interface RestoreUserRequest {
    id: string;
}

export interface RevokeAllUserSessionsRequest {
    id: string;
}

export interface RevokeUserAppRoleRequest {
    id: string;
    appRoleRef: AppRoleRef;
}

export interface RevokeUserSessionRequest {
    id: string;
    sessionId: string;
}

export interface SetUserPasswordRequest {
    id: string;
    setPasswordRequest: SetPasswordRequest;
}

export interface SetUserPlatformRoleRequest {
    id: string;
    setRoleRequest: SetRoleRequest;
}

export interface SetUserStatusRequest {
    id: string;
    userStatusRequest: UserStatusRequest;
}

export interface StartImpersonationRequest {
    id: string;
}

export interface StopImpersonationRequest {
    id: string;
}

export interface UnbanUserRequest {
    id: string;
}

export interface UpdateUserOperationRequest {
    id: string;
    updateUserRequest: UpdateUserRequest;
}

export interface UpdateUserMembershipsRequest {
    id: string;
    updateMembershipsRequest: UpdateMembershipsRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Add the user to an organization
     */
    async addUserMembershipRaw(requestParameters: AddUserMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkId>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addUserMembership().'
            );
        }

        if (requestParameters['addMembershipRequest'] == null) {
            throw new runtime.RequiredError(
                'addMembershipRequest',
                'Required parameter "addMembershipRequest" was null or undefined when calling addUserMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/memberships`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMembershipRequestToJSON(requestParameters['addMembershipRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkIdFromJSON(jsonValue));
    }

    /**
     * Add the user to an organization
     */
    async addUserMembership(requestParameters: AddUserMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkId> {
        const response = await this.addUserMembershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add the user to a group
     */
    async addUserToGroupRaw(requestParameters: AddUserToGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addUserToGroup().'
            );
        }

        if (requestParameters['userGroupRef'] == null) {
            throw new runtime.RequiredError(
                'userGroupRef',
                'Required parameter "userGroupRef" was null or undefined when calling addUserToGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/groups`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserGroupRefToJSON(requestParameters['userGroupRef']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Add the user to a group
     */
    async addUserToGroup(requestParameters: AddUserToGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.addUserToGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assign a role to the user in an org
     */
    async assignUserAppRoleRaw(requestParameters: AssignUserAppRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling assignUserAppRole().'
            );
        }

        if (requestParameters['appRoleRef'] == null) {
            throw new runtime.RequiredError(
                'appRoleRef',
                'Required parameter "appRoleRef" was null or undefined when calling assignUserAppRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/app-roles`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppRoleRefToJSON(requestParameters['appRoleRef']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Assign a role to the user in an org
     */
    async assignUserAppRole(requestParameters: AssignUserAppRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.assignUserAppRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ban a user (optionally temporary)
     */
    async banUserRaw(requestParameters: BanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling banUser().'
            );
        }

        if (requestParameters['banRequest'] == null) {
            throw new runtime.RequiredError(
                'banRequest',
                'Required parameter "banRequest" was null or undefined when calling banUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/ban`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BanRequestToJSON(requestParameters['banRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Ban a user (optionally temporary)
     */
    async banUser(requestParameters: BanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.banUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply an action to many users
     */
    async bulkUserActionRaw(requestParameters: BulkUserActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkUserResult>> {
        if (requestParameters['bulkUserRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkUserRequest',
                'Required parameter "bulkUserRequest" was null or undefined when calling bulkUserAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/bulk`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkUserRequestToJSON(requestParameters['bulkUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkUserResultFromJSON(jsonValue));
    }

    /**
     * Apply an action to many users
     */
    async bulkUserAction(requestParameters: BulkUserActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkUserResult> {
        const response = await this.bulkUserActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a user
     */
    async createUserRaw(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserCreated>> {
        if (requestParameters['createUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserRequest',
                'Required parameter "createUserRequest" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserCreatedFromJSON(jsonValue));
    }

    /**
     * Create a user
     */
    async createUser(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserCreated> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft-delete a user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ReasonRequestToJSON(requestParameters['reasonRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Soft-delete a user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read a user
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetailEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailEnvelopeFromJSON(jsonValue));
    }

    /**
     * Read a user
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetailEnvelope> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List a user\'s role assignments
     */
    async listUserAppRolesRaw(requestParameters: ListUserAppRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRoleAssignments>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listUserAppRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/app-roles`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRoleAssignmentsFromJSON(jsonValue));
    }

    /**
     * List a user\'s role assignments
     */
    async listUserAppRoles(requestParameters: ListUserAppRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRoleAssignments> {
        const response = await this.listUserAppRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the groups a user belongs to
     */
    async listUserGroupsRaw(requestParameters: ListUserGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGroups>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listUserGroups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/groups`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGroupsFromJSON(jsonValue));
    }

    /**
     * List the groups a user belongs to
     */
    async listUserGroups(requestParameters: ListUserGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGroups> {
        const response = await this.listUserGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List a user\'s organization memberships
     */
    async listUserMembershipsRaw(requestParameters: ListUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembershipList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listUserMemberships().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterOrganizationId'] != null) {
            queryParameters['filter[organization_id]'] = requestParameters['filterOrganizationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/memberships`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembershipListFromJSON(jsonValue));
    }

    /**
     * List a user\'s organization memberships
     */
    async listUserMemberships(requestParameters: ListUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembershipList> {
        const response = await this.listUserMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List a user\'s active sessions
     */
    async listUserSessionsRaw(requestParameters: ListUserSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionList>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listUserSessions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/sessions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionListFromJSON(jsonValue));
    }

    /**
     * List a user\'s active sessions
     */
    async listUserSessions(requestParameters: ListUserSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionList> {
        const response = await this.listUserSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List users
     */
    async listUsersRaw(requestParameters: ListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserListFromJSON(jsonValue));
    }

    /**
     * List users
     */
    async listUsers(requestParameters: ListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserList> {
        const response = await this.listUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove the user from a group
     */
    async removeUserFromGroupRaw(requestParameters: RemoveUserFromGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeUserFromGroup().'
            );
        }

        if (requestParameters['userGroupRef'] == null) {
            throw new runtime.RequiredError(
                'userGroupRef',
                'Required parameter "userGroupRef" was null or undefined when calling removeUserFromGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/groups`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UserGroupRefToJSON(requestParameters['userGroupRef']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Remove the user from a group
     */
    async removeUserFromGroup(requestParameters: RemoveUserFromGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.removeUserFromGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Bulk-remove memberships
     */
    async removeUserMembershipsRaw(requestParameters: RemoveUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkCount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeUserMemberships().'
            );
        }

        if (requestParameters['deleteMembershipsRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteMembershipsRequest',
                'Required parameter "deleteMembershipsRequest" was null or undefined when calling removeUserMemberships().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/memberships`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteMembershipsRequestToJSON(requestParameters['deleteMembershipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkCountFromJSON(jsonValue));
    }

    /**
     * Bulk-remove memberships
     */
    async removeUserMemberships(requestParameters: RemoveUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkCount> {
        const response = await this.removeUserMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restore a soft-deleted user
     */
    async restoreUserRaw(requestParameters: RestoreUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling restoreUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/restore`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkStatusFromJSON(jsonValue));
    }

    /**
     * Restore a soft-deleted user
     */
    async restoreUser(requestParameters: RestoreUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkStatus> {
        const response = await this.restoreUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke all of a user\'s sessions
     */
    async revokeAllUserSessionsRaw(requestParameters: RevokeAllUserSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeAllUserSessions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/sessions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Revoke all of a user\'s sessions
     */
    async revokeAllUserSessions(requestParameters: RevokeAllUserSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.revokeAllUserSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a role assignment
     */
    async revokeUserAppRoleRaw(requestParameters: RevokeUserAppRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeUserAppRole().'
            );
        }

        if (requestParameters['appRoleRef'] == null) {
            throw new runtime.RequiredError(
                'appRoleRef',
                'Required parameter "appRoleRef" was null or undefined when calling revokeUserAppRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/app-roles`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AppRoleRefToJSON(requestParameters['appRoleRef']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Revoke a role assignment
     */
    async revokeUserAppRole(requestParameters: RevokeUserAppRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.revokeUserAppRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a single session
     */
    async revokeUserSessionRaw(requestParameters: RevokeUserSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeUserSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling revokeUserSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/sessions/{sessionId}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Revoke a single session
     */
    async revokeUserSession(requestParameters: RevokeUserSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.revokeUserSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set a password directly or send a reset email
     */
    async setUserPasswordRaw(requestParameters: SetUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetUserPassword200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setUserPassword().'
            );
        }

        if (requestParameters['setPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'setPasswordRequest',
                'Required parameter "setPasswordRequest" was null or undefined when calling setUserPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/password`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetPasswordRequestToJSON(requestParameters['setPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetUserPassword200ResponseFromJSON(jsonValue));
    }

    /**
     * Set a password directly or send a reset email
     */
    async setUserPassword(requestParameters: SetUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetUserPassword200Response> {
        const response = await this.setUserPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set the Better Auth platform role (superadmin only)
     */
    async setUserPlatformRoleRaw(requestParameters: SetUserPlatformRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetUserPlatformRole200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setUserPlatformRole().'
            );
        }

        if (requestParameters['setRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'setRoleRequest',
                'Required parameter "setRoleRequest" was null or undefined when calling setUserPlatformRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/role`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetRoleRequestToJSON(requestParameters['setRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetUserPlatformRole200ResponseFromJSON(jsonValue));
    }

    /**
     * Set the Better Auth platform role (superadmin only)
     */
    async setUserPlatformRole(requestParameters: SetUserPlatformRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetUserPlatformRole200Response> {
        const response = await this.setUserPlatformRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Approve / block / suspend / reactivate a user
     */
    async setUserStatusRaw(requestParameters: SetUserStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setUserStatus().'
            );
        }

        if (requestParameters['userStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'userStatusRequest',
                'Required parameter "userStatusRequest" was null or undefined when calling setUserStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserStatusRequestToJSON(requestParameters['userStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkStatusFromJSON(jsonValue));
    }

    /**
     * Approve / block / suspend / reactivate a user
     */
    async setUserStatus(requestParameters: SetUserStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkStatus> {
        const response = await this.setUserStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start impersonating a user (sets cookies)
     */
    async startImpersonationRaw(requestParameters: StartImpersonationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startImpersonation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/impersonate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Start impersonating a user (sets cookies)
     */
    async startImpersonation(requestParameters: StartImpersonationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.startImpersonationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop impersonating
     */
    async stopImpersonationRaw(requestParameters: StopImpersonationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stopImpersonation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/impersonate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Stop impersonating
     */
    async stopImpersonation(requestParameters: StopImpersonationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.stopImpersonationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unban a user
     */
    async unbanUserRaw(requestParameters: UnbanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unbanUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}/unban`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Unban a user
     */
    async unbanUser(requestParameters: UnbanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.unbanUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a user\'s display name / locale
     */
    async updateUserRaw(requestParameters: UpdateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ok>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateUser().'
            );
        }

        if (requestParameters['updateUserRequest'] == null) {
            throw new runtime.RequiredError(
                'updateUserRequest',
                'Required parameter "updateUserRequest" was null or undefined when calling updateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkFromJSON(jsonValue));
    }

    /**
     * Update a user\'s display name / locale
     */
    async updateUser(requestParameters: UpdateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ok> {
        const response = await this.updateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Bulk-update membership statuses
     */
    async updateUserMembershipsRaw(requestParameters: UpdateUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OkCount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateUserMemberships().'
            );
        }

        if (requestParameters['updateMembershipsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMembershipsRequest',
                'Required parameter "updateMembershipsRequest" was null or undefined when calling updateUserMemberships().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/memberships`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMembershipsRequestToJSON(requestParameters['updateMembershipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OkCountFromJSON(jsonValue));
    }

    /**
     * Bulk-update membership statuses
     */
    async updateUserMemberships(requestParameters: UpdateUserMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OkCount> {
        const response = await this.updateUserMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
