/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddOrgMemberRequest
 */
export interface AddOrgMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddOrgMemberRequest
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof AddOrgMemberRequest
     */
    status?: AddOrgMemberRequestStatusEnum;
}


/**
 * @export
 */
export const AddOrgMemberRequestStatusEnum = {
    Active: 'active',
    PendingApproval: 'pending_approval',
    Blocked: 'blocked',
    Suspended: 'suspended'
} as const;
export type AddOrgMemberRequestStatusEnum = typeof AddOrgMemberRequestStatusEnum[keyof typeof AddOrgMemberRequestStatusEnum];


/**
 * Check if a given object implements the AddOrgMemberRequest interface.
 */
export function instanceOfAddOrgMemberRequest(value: object): value is AddOrgMemberRequest {
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    return true;
}

export function AddOrgMemberRequestFromJSON(json: any): AddOrgMemberRequest {
    return AddOrgMemberRequestFromJSONTyped(json, false);
}

export function AddOrgMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrgMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appUserId': json['appUserId'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AddOrgMemberRequestToJSON(json: any): AddOrgMemberRequest {
    return AddOrgMemberRequestToJSONTyped(json, false);
}

export function AddOrgMemberRequestToJSONTyped(value?: AddOrgMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appUserId': value['appUserId'],
        'status': value['status'],
    };
}

