/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Administrator error envelope. `adminErrorResponse` may spread extra non-secret fields for specific codes — see `RateLimitedError` / `UnprocessableError`.
 * @export
 * @interface AdminError
 */
export interface AdminError {
    [key: string]: any | any;
    /**
     * Machine-readable code.
     * @type {string}
     * @memberof AdminError
     */
    error: string;
    /**
     * i18n message key.
     * @type {string}
     * @memberof AdminError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof AdminError
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminError interface.
 */
export function instanceOfAdminError(value: object): value is AdminError {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminErrorFromJSON(json: any): AdminError {
    return AdminErrorFromJSONTyped(json, false);
}

export function AdminErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'error': json['error'],
        'message': json['message'],
        'requestId': json['requestId'],
    };
}

export function AdminErrorToJSON(json: any): AdminError {
    return AdminErrorToJSONTyped(json, false);
}

export function AdminErrorToJSONTyped(value?: AdminError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'error': value['error'],
        'message': value['message'],
        'requestId': value['requestId'],
    };
}

