/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminApiKeyDetail
 */
export interface AdminApiKeyDetail {
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    appUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    ownerName?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    keyPrefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminApiKeyDetail
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    status: AdminApiKeyDetailStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyDetail
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyDetail
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    lastUsedIp?: string;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyDetail
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyDetail
     */
    revokedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    revokedReason?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    createdByEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyDetail
     */
    revokedByEmail?: string | null;
}


/**
 * @export
 */
export const AdminApiKeyDetailStatusEnum = {
    Active: 'active',
    Revoked: 'revoked'
} as const;
export type AdminApiKeyDetailStatusEnum = typeof AdminApiKeyDetailStatusEnum[keyof typeof AdminApiKeyDetailStatusEnum];


/**
 * Check if a given object implements the AdminApiKeyDetail interface.
 */
export function instanceOfAdminApiKeyDetail(value: object): value is AdminApiKeyDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('keyPrefix' in value) || value['keyPrefix'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AdminApiKeyDetailFromJSON(json: any): AdminApiKeyDetail {
    return AdminApiKeyDetailFromJSONTyped(json, false);
}

export function AdminApiKeyDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminApiKeyDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appUserId': json['app_user_id'] == null ? undefined : json['app_user_id'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'ownerName': json['owner_name'] == null ? undefined : json['owner_name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'name': json['name'],
        'keyPrefix': json['key_prefix'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'status': json['status'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'lastUsedIp': json['last_used_ip'] == null ? undefined : json['last_used_ip'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'revokedAt': json['revoked_at'] == null ? undefined : (new Date(json['revoked_at'])),
        'revokedReason': json['revoked_reason'] == null ? undefined : json['revoked_reason'],
        'createdByEmail': json['created_by_email'] == null ? undefined : json['created_by_email'],
        'revokedByEmail': json['revoked_by_email'] == null ? undefined : json['revoked_by_email'],
    };
}

export function AdminApiKeyDetailToJSON(json: any): AdminApiKeyDetail {
    return AdminApiKeyDetailToJSONTyped(json, false);
}

export function AdminApiKeyDetailToJSONTyped(value?: AdminApiKeyDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'app_user_id': value['appUserId'],
        'owner_email': value['ownerEmail'],
        'owner_name': value['ownerName'],
        'organization_id': value['organizationId'],
        'name': value['name'],
        'key_prefix': value['keyPrefix'],
        'scopes': value['scopes'],
        'status': value['status'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'last_used_at': value['lastUsedAt'] == null ? undefined : ((value['lastUsedAt']).toISOString()),
        'last_used_ip': value['lastUsedIp'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'revoked_at': value['revokedAt'] == null ? undefined : ((value['revokedAt']).toISOString()),
        'revoked_reason': value['revokedReason'],
        'created_by_email': value['createdByEmail'],
        'revoked_by_email': value['revokedByEmail'],
    };
}

