/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminApiKeyItem
 */
export interface AdminApiKeyItem {
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    appUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    ownerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    keyPrefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminApiKeyItem
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    status: AdminApiKeyItemStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyItem
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyItem
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    lastUsedIp?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyItem
     */
    revokedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyItem
     */
    revokedReason?: string | null;
}


/**
 * @export
 */
export const AdminApiKeyItemStatusEnum = {
    Active: 'active',
    Revoked: 'revoked'
} as const;
export type AdminApiKeyItemStatusEnum = typeof AdminApiKeyItemStatusEnum[keyof typeof AdminApiKeyItemStatusEnum];


/**
 * Check if a given object implements the AdminApiKeyItem interface.
 */
export function instanceOfAdminApiKeyItem(value: object): value is AdminApiKeyItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('keyPrefix' in value) || value['keyPrefix'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AdminApiKeyItemFromJSON(json: any): AdminApiKeyItem {
    return AdminApiKeyItemFromJSONTyped(json, false);
}

export function AdminApiKeyItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminApiKeyItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appUserId': json['app_user_id'] == null ? undefined : json['app_user_id'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'ownerName': json['owner_name'] == null ? undefined : json['owner_name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'name': json['name'],
        'keyPrefix': json['key_prefix'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'status': json['status'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'lastUsedIp': json['last_used_ip'] == null ? undefined : json['last_used_ip'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'revokedAt': json['revoked_at'] == null ? undefined : (new Date(json['revoked_at'])),
        'revokedReason': json['revoked_reason'] == null ? undefined : json['revoked_reason'],
    };
}

export function AdminApiKeyItemToJSON(json: any): AdminApiKeyItem {
    return AdminApiKeyItemToJSONTyped(json, false);
}

export function AdminApiKeyItemToJSONTyped(value?: AdminApiKeyItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'app_user_id': value['appUserId'],
        'owner_email': value['ownerEmail'],
        'owner_name': value['ownerName'],
        'organization_id': value['organizationId'],
        'name': value['name'],
        'key_prefix': value['keyPrefix'],
        'scopes': value['scopes'],
        'status': value['status'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'last_used_at': value['lastUsedAt'] == null ? undefined : ((value['lastUsedAt'] as any).toISOString()),
        'last_used_ip': value['lastUsedIp'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'revoked_at': value['revokedAt'] == null ? undefined : ((value['revokedAt'] as any).toISOString()),
        'revoked_reason': value['revokedReason'],
    };
}

