/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminApiKeyRevoked
 */
export interface AdminApiKeyRevoked {
    /**
     * 
     * @type {boolean}
     * @memberof AdminApiKeyRevoked
     */
    ok: AdminApiKeyRevokedOkEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AdminApiKeyRevoked
     */
    alreadyRevoked: boolean;
}


/**
 * @export
 */
export const AdminApiKeyRevokedOkEnum = {
    True: true
} as const;
export type AdminApiKeyRevokedOkEnum = typeof AdminApiKeyRevokedOkEnum[keyof typeof AdminApiKeyRevokedOkEnum];


/**
 * Check if a given object implements the AdminApiKeyRevoked interface.
 */
export function instanceOfAdminApiKeyRevoked(value: object): value is AdminApiKeyRevoked {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('alreadyRevoked' in value) || value['alreadyRevoked'] === undefined) return false;
    return true;
}

export function AdminApiKeyRevokedFromJSON(json: any): AdminApiKeyRevoked {
    return AdminApiKeyRevokedFromJSONTyped(json, false);
}

export function AdminApiKeyRevokedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminApiKeyRevoked {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'alreadyRevoked': json['alreadyRevoked'],
    };
}

export function AdminApiKeyRevokedToJSON(json: any): AdminApiKeyRevoked {
    return AdminApiKeyRevokedToJSONTyped(json, false);
}

export function AdminApiKeyRevokedToJSONTyped(value?: AdminApiKeyRevoked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'alreadyRevoked': value['alreadyRevoked'],
    };
}

