/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminApiKeyCreated
 */
export interface AdminApiKeyCreated {
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyCreated
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyCreated
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminApiKeyCreated
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminApiKeyCreated
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof AdminApiKeyCreated
     */
    expiresAt?: Date | null;
    /**
     * Plaintext secret — shown once.
     * @type {string}
     * @memberof AdminApiKeyCreated
     */
    key: string;
}

/**
 * Check if a given object implements the AdminApiKeyCreated interface.
 */
export function instanceOfAdminApiKeyCreated(value: object): value is AdminApiKeyCreated {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function AdminApiKeyCreatedFromJSON(json: any): AdminApiKeyCreated {
    return AdminApiKeyCreatedFromJSONTyped(json, false);
}

export function AdminApiKeyCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminApiKeyCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'prefix': json['prefix'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'key': json['key'],
    };
}

export function AdminApiKeyCreatedToJSON(json: any): AdminApiKeyCreated {
    return AdminApiKeyCreatedToJSONTyped(json, false);
}

export function AdminApiKeyCreatedToJSONTyped(value?: AdminApiKeyCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'prefix': value['prefix'],
        'scopes': value['scopes'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'key': value['key'],
    };
}

