/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoleAssignment } from './AppRoleAssignment';
import {
    AppRoleAssignmentFromJSON,
    AppRoleAssignmentFromJSONTyped,
    AppRoleAssignmentToJSON,
    AppRoleAssignmentToJSONTyped,
} from './AppRoleAssignment';

/**
 * 
 * @export
 * @interface AppRoleAssignments
 */
export interface AppRoleAssignments {
    /**
     * 
     * @type {Array<AppRoleAssignment>}
     * @memberof AppRoleAssignments
     */
    assignments: Array<AppRoleAssignment>;
}

/**
 * Check if a given object implements the AppRoleAssignments interface.
 */
export function instanceOfAppRoleAssignments(value: object): value is AppRoleAssignments {
    if (!('assignments' in value) || value['assignments'] === undefined) return false;
    return true;
}

export function AppRoleAssignmentsFromJSON(json: any): AppRoleAssignments {
    return AppRoleAssignmentsFromJSONTyped(json, false);
}

export function AppRoleAssignmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoleAssignments {
    if (json == null) {
        return json;
    }
    return {
        
        'assignments': ((json['assignments'] as Array<any>).map(AppRoleAssignmentFromJSON)),
    };
}

export function AppRoleAssignmentsToJSON(json: any): AppRoleAssignments {
    return AppRoleAssignmentsToJSONTyped(json, false);
}

export function AppRoleAssignmentsToJSONTyped(value?: AppRoleAssignments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignments': ((value['assignments'] as Array<any>).map(AppRoleAssignmentToJSON)),
    };
}

