/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppRoleRef
 */
export interface AppRoleRef {
    /**
     * 
     * @type {string}
     * @memberof AppRoleRef
     */
    roleId: string;
    /**
     * 
     * @type {string}
     * @memberof AppRoleRef
     */
    organizationId: string;
}

/**
 * Check if a given object implements the AppRoleRef interface.
 */
export function instanceOfAppRoleRef(value: object): value is AppRoleRef {
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function AppRoleRefFromJSON(json: any): AppRoleRef {
    return AppRoleRefFromJSONTyped(json, false);
}

export function AppRoleRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoleRef {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['roleId'],
        'organizationId': json['organizationId'],
    };
}

export function AppRoleRefToJSON(json: any): AppRoleRef {
    return AppRoleRefToJSONTyped(json, false);
}

export function AppRoleRefToJSONTyped(value?: AppRoleRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roleId': value['roleId'],
        'organizationId': value['organizationId'],
    };
}

