/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The raw policy override row; null when the organization inherits the platform default.
 * @export
 * @interface AuthPolicySettings
 */
export interface AuthPolicySettings {
    /**
     * 
     * @type {string}
     * @memberof AuthPolicySettings
     */
    organizationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthPolicySettings
     */
    requireEmailVerification: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthPolicySettings
     */
    signupApprovalMode: AuthPolicySettingsSignupApprovalModeEnum;
    /**
     * null = every enabled auth method is accepted.
     * @type {Array<string>}
     * @memberof AuthPolicySettings
     */
    allowedAuthMethods?: Array<AuthPolicySettingsAllowedAuthMethodsEnum> | null;
    /**
     * Lowercased domains; null = no domain auto-approval.
     * @type {Array<string>}
     * @memberof AuthPolicySettings
     */
    autoApproveEmailDomains?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthPolicySettings
     */
    updatedAt?: Date | null;
}


/**
 * @export
 */
export const AuthPolicySettingsSignupApprovalModeEnum = {
    AdminApproval: 'admin_approval',
    AutoActive: 'auto_active',
    InviteOnly: 'invite_only'
} as const;
export type AuthPolicySettingsSignupApprovalModeEnum = typeof AuthPolicySettingsSignupApprovalModeEnum[keyof typeof AuthPolicySettingsSignupApprovalModeEnum];

/**
 * @export
 */
export const AuthPolicySettingsAllowedAuthMethodsEnum = {
    Email: 'email',
    Google: 'google',
    Microsoft: 'microsoft',
    Github: 'github'
} as const;
export type AuthPolicySettingsAllowedAuthMethodsEnum = typeof AuthPolicySettingsAllowedAuthMethodsEnum[keyof typeof AuthPolicySettingsAllowedAuthMethodsEnum];


/**
 * Check if a given object implements the AuthPolicySettings interface.
 */
export function instanceOfAuthPolicySettings(value: object): value is AuthPolicySettings {
    if (!('requireEmailVerification' in value) || value['requireEmailVerification'] === undefined) return false;
    if (!('signupApprovalMode' in value) || value['signupApprovalMode'] === undefined) return false;
    return true;
}

export function AuthPolicySettingsFromJSON(json: any): AuthPolicySettings {
    return AuthPolicySettingsFromJSONTyped(json, false);
}

export function AuthPolicySettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPolicySettings {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'requireEmailVerification': json['requireEmailVerification'],
        'signupApprovalMode': json['signupApprovalMode'],
        'allowedAuthMethods': json['allowedAuthMethods'] == null ? undefined : json['allowedAuthMethods'],
        'autoApproveEmailDomains': json['autoApproveEmailDomains'] == null ? undefined : json['autoApproveEmailDomains'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AuthPolicySettingsToJSON(json: any): AuthPolicySettings {
    return AuthPolicySettingsToJSONTyped(json, false);
}

export function AuthPolicySettingsToJSONTyped(value?: AuthPolicySettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'requireEmailVerification': value['requireEmailVerification'],
        'signupApprovalMode': value['signupApprovalMode'],
        'allowedAuthMethods': value['allowedAuthMethods'],
        'autoApproveEmailDomains': value['autoApproveEmailDomains'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

