/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The resolved policy that actually governs sign-ups for this scope.
 * @export
 * @interface AuthPolicyEffective
 */
export interface AuthPolicyEffective {
    /**
     * 
     * @type {boolean}
     * @memberof AuthPolicyEffective
     */
    requireEmailVerification: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthPolicyEffective
     */
    signupApprovalMode: AuthPolicyEffectiveSignupApprovalModeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthPolicyEffective
     */
    allowedAuthMethods?: Array<AuthPolicyEffectiveAllowedAuthMethodsEnum> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthPolicyEffective
     */
    autoApproveEmailDomains?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AuthPolicyEffective
     */
    source: AuthPolicyEffectiveSourceEnum;
}


/**
 * @export
 */
export const AuthPolicyEffectiveSignupApprovalModeEnum = {
    AdminApproval: 'admin_approval',
    AutoActive: 'auto_active',
    InviteOnly: 'invite_only'
} as const;
export type AuthPolicyEffectiveSignupApprovalModeEnum = typeof AuthPolicyEffectiveSignupApprovalModeEnum[keyof typeof AuthPolicyEffectiveSignupApprovalModeEnum];

/**
 * @export
 */
export const AuthPolicyEffectiveAllowedAuthMethodsEnum = {
    Email: 'email',
    Google: 'google',
    Microsoft: 'microsoft',
    Github: 'github'
} as const;
export type AuthPolicyEffectiveAllowedAuthMethodsEnum = typeof AuthPolicyEffectiveAllowedAuthMethodsEnum[keyof typeof AuthPolicyEffectiveAllowedAuthMethodsEnum];

/**
 * @export
 */
export const AuthPolicyEffectiveSourceEnum = {
    Organization: 'organization',
    PlatformDefault: 'platform_default',
    FailClosed: 'fail_closed'
} as const;
export type AuthPolicyEffectiveSourceEnum = typeof AuthPolicyEffectiveSourceEnum[keyof typeof AuthPolicyEffectiveSourceEnum];


/**
 * Check if a given object implements the AuthPolicyEffective interface.
 */
export function instanceOfAuthPolicyEffective(value: object): value is AuthPolicyEffective {
    if (!('requireEmailVerification' in value) || value['requireEmailVerification'] === undefined) return false;
    if (!('signupApprovalMode' in value) || value['signupApprovalMode'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function AuthPolicyEffectiveFromJSON(json: any): AuthPolicyEffective {
    return AuthPolicyEffectiveFromJSONTyped(json, false);
}

export function AuthPolicyEffectiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPolicyEffective {
    if (json == null) {
        return json;
    }
    return {
        
        'requireEmailVerification': json['requireEmailVerification'],
        'signupApprovalMode': json['signupApprovalMode'],
        'allowedAuthMethods': json['allowedAuthMethods'] == null ? undefined : json['allowedAuthMethods'],
        'autoApproveEmailDomains': json['autoApproveEmailDomains'] == null ? undefined : json['autoApproveEmailDomains'],
        'source': json['source'],
    };
}

export function AuthPolicyEffectiveToJSON(json: any): AuthPolicyEffective {
    return AuthPolicyEffectiveToJSONTyped(json, false);
}

export function AuthPolicyEffectiveToJSONTyped(value?: AuthPolicyEffective | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requireEmailVerification': value['requireEmailVerification'],
        'signupApprovalMode': value['signupApprovalMode'],
        'allowedAuthMethods': value['allowedAuthMethods'],
        'autoApproveEmailDomains': value['autoApproveEmailDomains'],
        'source': value['source'],
    };
}

