/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BanRequest
 */
export interface BanRequest {
    /**
     * 
     * @type {string}
     * @memberof BanRequest
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof BanRequest
     */
    expiresInSeconds?: number;
}

/**
 * Check if a given object implements the BanRequest interface.
 */
export function instanceOfBanRequest(value: object): value is BanRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function BanRequestFromJSON(json: any): BanRequest {
    return BanRequestFromJSONTyped(json, false);
}

export function BanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'expiresInSeconds': json['expiresInSeconds'] == null ? undefined : json['expiresInSeconds'],
    };
}

export function BanRequestToJSON(json: any): BanRequest {
    return BanRequestToJSONTyped(json, false);
}

export function BanRequestToJSONTyped(value?: BanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'expiresInSeconds': value['expiresInSeconds'],
    };
}

