/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Selection filters for `ids: "*"` (ignored for an explicit id list).
 * @export
 * @interface BulkUserRequestFilters
 */
export interface BulkUserRequestFilters {
    [key: string]: any | any;
    /**
     * A list of statuses, or one status as a bare string.
     * @type {Array<string>}
     * @memberof BulkUserRequestFilters
     */
    status?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BulkUserRequestFilters
     */
    q?: string;
}

/**
 * Check if a given object implements the BulkUserRequestFilters interface.
 */
export function instanceOfBulkUserRequestFilters(value: object): value is BulkUserRequestFilters {
    return true;
}

export function BulkUserRequestFiltersFromJSON(json: any): BulkUserRequestFilters {
    return BulkUserRequestFiltersFromJSONTyped(json, false);
}

export function BulkUserRequestFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUserRequestFilters {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': json['status'] == null ? undefined : json['status'],
        'q': json['q'] == null ? undefined : json['q'],
    };
}

export function BulkUserRequestFiltersToJSON(json: any): BulkUserRequestFilters {
    return BulkUserRequestFiltersToJSONTyped(json, false);
}

export function BulkUserRequestFiltersToJSONTyped(value?: BulkUserRequestFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'status': value['status'],
        'q': value['q'],
    };
}

