/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkUserResultResultsInner
 */
export interface BulkUserResultResultsInner {
    /**
     * 
     * @type {boolean}
     * @memberof BulkUserResultResultsInner
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof BulkUserResultResultsInner
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUserResultResultsInner
     */
    error?: string;
}

/**
 * Check if a given object implements the BulkUserResultResultsInner interface.
 */
export function instanceOfBulkUserResultResultsInner(value: object): value is BulkUserResultResultsInner {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    return true;
}

export function BulkUserResultResultsInnerFromJSON(json: any): BulkUserResultResultsInner {
    return BulkUserResultResultsInnerFromJSONTyped(json, false);
}

export function BulkUserResultResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUserResultResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'appUserId': json['appUserId'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function BulkUserResultResultsInnerToJSON(json: any): BulkUserResultResultsInner {
    return BulkUserResultResultsInnerToJSONTyped(json, false);
}

export function BulkUserResultResultsInnerToJSONTyped(value?: BulkUserResultResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'appUserId': value['appUserId'],
        'error': value['error'],
    };
}

