/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkUserRequestFilters
 */
export interface BulkUserRequestFilters {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkUserRequestFilters
     */
    status?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BulkUserRequestFilters
     */
    q?: string;
}

/**
 * Check if a given object implements the BulkUserRequestFilters interface.
 */
export function instanceOfBulkUserRequestFilters(value: object): value is BulkUserRequestFilters {
    return true;
}

export function BulkUserRequestFiltersFromJSON(json: any): BulkUserRequestFilters {
    return BulkUserRequestFiltersFromJSONTyped(json, false);
}

export function BulkUserRequestFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUserRequestFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'q': json['q'] == null ? undefined : json['q'],
    };
}

export function BulkUserRequestFiltersToJSON(json: any): BulkUserRequestFilters {
    return BulkUserRequestFiltersToJSONTyped(json, false);
}

export function BulkUserRequestFiltersToJSONTyped(value?: BulkUserRequestFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'q': value['q'],
    };
}

