/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkUserRequestFilters } from './BulkUserRequestFilters';
import {
    BulkUserRequestFiltersFromJSON,
    BulkUserRequestFiltersFromJSONTyped,
    BulkUserRequestFiltersToJSON,
    BulkUserRequestFiltersToJSONTyped,
} from './BulkUserRequestFilters';

/**
 * 
 * @export
 * @interface BulkUserRequest
 */
export interface BulkUserRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof BulkUserRequest
     */
    action: BulkUserRequestActionEnum;
    /**
     * 1–500 app user ids, or the string `*` (the only accepted string) to select by `filters`.
     * @type {Array<string>}
     * @memberof BulkUserRequest
     */
    ids: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BulkUserRequest
     */
    reason?: string;
    /**
     * 
     * @type {number}
     * @memberof BulkUserRequest
     */
    expiresInSeconds?: number;
    /**
     * 
     * @type {BulkUserRequestFilters}
     * @memberof BulkUserRequest
     */
    filters?: BulkUserRequestFilters;
}


/**
 * @export
 */
export const BulkUserRequestActionEnum = {
    Approve: 'approve',
    Block: 'block',
    Suspend: 'suspend',
    Reactivate: 'reactivate',
    Ban: 'ban',
    Unban: 'unban',
    SoftDelete: 'soft_delete',
    Restore: 'restore'
} as const;
export type BulkUserRequestActionEnum = typeof BulkUserRequestActionEnum[keyof typeof BulkUserRequestActionEnum];


/**
 * Check if a given object implements the BulkUserRequest interface.
 */
export function instanceOfBulkUserRequest(value: object): value is BulkUserRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function BulkUserRequestFromJSON(json: any): BulkUserRequest {
    return BulkUserRequestFromJSONTyped(json, false);
}

export function BulkUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'action': json['action'],
        'ids': json['ids'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'expiresInSeconds': json['expiresInSeconds'] == null ? undefined : json['expiresInSeconds'],
        'filters': json['filters'] == null ? undefined : BulkUserRequestFiltersFromJSON(json['filters']),
    };
}

export function BulkUserRequestToJSON(json: any): BulkUserRequest {
    return BulkUserRequestToJSONTyped(json, false);
}

export function BulkUserRequestToJSONTyped(value?: BulkUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'action': value['action'],
        'ids': value['ids'],
        'reason': value['reason'],
        'expiresInSeconds': value['expiresInSeconds'],
        'filters': BulkUserRequestFiltersToJSON(value['filters']),
    };
}

