/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseAppRequest
 */
export interface CreateEnterpriseAppRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    origin: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    subdomain: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    ssoAudience: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    status?: CreateEnterpriseAppRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateEnterpriseAppRequest
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseAppRequest
     */
    organizationId?: string | null;
}


/**
 * @export
 */
export const CreateEnterpriseAppRequestStatusEnum = {
    Available: 'available',
    Disabled: 'disabled'
} as const;
export type CreateEnterpriseAppRequestStatusEnum = typeof CreateEnterpriseAppRequestStatusEnum[keyof typeof CreateEnterpriseAppRequestStatusEnum];


/**
 * Check if a given object implements the CreateEnterpriseAppRequest interface.
 */
export function instanceOfCreateEnterpriseAppRequest(value: object): value is CreateEnterpriseAppRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('subdomain' in value) || value['subdomain'] === undefined) return false;
    if (!('ssoAudience' in value) || value['ssoAudience'] === undefined) return false;
    return true;
}

export function CreateEnterpriseAppRequestFromJSON(json: any): CreateEnterpriseAppRequest {
    return CreateEnterpriseAppRequestFromJSONTyped(json, false);
}

export function CreateEnterpriseAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'description': json['description'] == null ? undefined : json['description'],
        'origin': json['origin'],
        'subdomain': json['subdomain'],
        'ssoAudience': json['sso_audience'],
        'status': json['status'] == null ? undefined : json['status'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
    };
}

export function CreateEnterpriseAppRequestToJSON(json: any): CreateEnterpriseAppRequest {
    return CreateEnterpriseAppRequestToJSONTyped(json, false);
}

export function CreateEnterpriseAppRequestToJSONTyped(value?: CreateEnterpriseAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'description': value['description'],
        'origin': value['origin'],
        'subdomain': value['subdomain'],
        'sso_audience': value['ssoAudience'],
        'status': value['status'],
        'sort_order': value['sortOrder'],
        'organization_id': value['organizationId'],
    };
}

