/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdminApiKeyRequest
 */
export interface CreateAdminApiKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAdminApiKeyRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminApiKeyRequest
     */
    ownerAppUserId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAdminApiKeyRequest
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateAdminApiKeyRequest
     */
    expiresInDays?: number;
}

/**
 * Check if a given object implements the CreateAdminApiKeyRequest interface.
 */
export function instanceOfCreateAdminApiKeyRequest(value: object): value is CreateAdminApiKeyRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ownerAppUserId' in value) || value['ownerAppUserId'] === undefined) return false;
    return true;
}

export function CreateAdminApiKeyRequestFromJSON(json: any): CreateAdminApiKeyRequest {
    return CreateAdminApiKeyRequestFromJSONTyped(json, false);
}

export function CreateAdminApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdminApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ownerAppUserId': json['ownerAppUserId'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'expiresInDays': json['expiresInDays'] == null ? undefined : json['expiresInDays'],
    };
}

export function CreateAdminApiKeyRequestToJSON(json: any): CreateAdminApiKeyRequest {
    return CreateAdminApiKeyRequestToJSONTyped(json, false);
}

export function CreateAdminApiKeyRequestToJSONTyped(value?: CreateAdminApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ownerAppUserId': value['ownerAppUserId'],
        'scopes': value['scopes'],
        'expiresInDays': value['expiresInDays'],
    };
}

