/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailTemplate
 */
export interface EmailTemplate {
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    locale: string;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    bodyHtml?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    bodyText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplate
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EmailTemplate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmailTemplate
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the EmailTemplate interface.
 */
export function instanceOfEmailTemplate(value: object): value is EmailTemplate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function EmailTemplateFromJSON(json: any): EmailTemplate {
    return EmailTemplateFromJSONTyped(json, false);
}

export function EmailTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'locale': json['locale'],
        'subject': json['subject'],
        'bodyHtml': json['body_html'] == null ? undefined : json['body_html'],
        'bodyText': json['body_text'] == null ? undefined : json['body_text'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function EmailTemplateToJSON(json: any): EmailTemplate {
    return EmailTemplateToJSONTyped(json, false);
}

export function EmailTemplateToJSONTyped(value?: EmailTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'locale': value['locale'],
        'subject': value['subject'],
        'body_html': value['bodyHtml'],
        'body_text': value['bodyText'],
        'description': value['description'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

