/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnterpriseAppItem
 */
export interface EnterpriseAppItem {
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    origin: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    subdomain: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    ssoAudience: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof EnterpriseAppItem
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseAppItem
     */
    organizationSlug?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EnterpriseAppItem
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the EnterpriseAppItem interface.
 */
export function instanceOfEnterpriseAppItem(value: object): value is EnterpriseAppItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('subdomain' in value) || value['subdomain'] === undefined) return false;
    if (!('ssoAudience' in value) || value['ssoAudience'] === undefined) return false;
    return true;
}

export function EnterpriseAppItemFromJSON(json: any): EnterpriseAppItem {
    return EnterpriseAppItemFromJSONTyped(json, false);
}

export function EnterpriseAppItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterpriseAppItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'description': json['description'] == null ? undefined : json['description'],
        'origin': json['origin'],
        'subdomain': json['subdomain'],
        'ssoAudience': json['sso_audience'],
        'status': json['status'] == null ? undefined : json['status'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'organizationSlug': json['organization_slug'] == null ? undefined : json['organization_slug'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function EnterpriseAppItemToJSON(json: any): EnterpriseAppItem {
    return EnterpriseAppItemToJSONTyped(json, false);
}

export function EnterpriseAppItemToJSONTyped(value?: EnterpriseAppItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'description': value['description'],
        'origin': value['origin'],
        'subdomain': value['subdomain'],
        'sso_audience': value['ssoAudience'],
        'status': value['status'],
        'sort_order': value['sortOrder'],
        'organization_id': value['organizationId'],
        'organization_slug': value['organizationSlug'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

