/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EraseUser200Response
 */
export interface EraseUser200Response {
    /**
     * 
     * @type {any}
     * @memberof EraseUser200Response
     */
    ok: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof EraseUser200Response
     */
    alreadyErased: boolean;
}

/**
 * Check if a given object implements the EraseUser200Response interface.
 */
export function instanceOfEraseUser200Response(value: object): value is EraseUser200Response {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('alreadyErased' in value) || value['alreadyErased'] === undefined) return false;
    return true;
}

export function EraseUser200ResponseFromJSON(json: any): EraseUser200Response {
    return EraseUser200ResponseFromJSONTyped(json, false);
}

export function EraseUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EraseUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'alreadyErased': json['alreadyErased'],
    };
}

export function EraseUser200ResponseToJSON(json: any): EraseUser200Response {
    return EraseUser200ResponseToJSONTyped(json, false);
}

export function EraseUser200ResponseToJSONTyped(value?: EraseUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'alreadyErased': value['alreadyErased'],
    };
}

