/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalMembershipItem
 */
export interface GlobalMembershipItem {
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    organizationSlug?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    organizationName?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    userDisplayName?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    status: GlobalMembershipItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    sourceProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GlobalMembershipItem
     */
    providerOrganizationKey?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GlobalMembershipItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GlobalMembershipItem
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const GlobalMembershipItemStatusEnum = {
    Active: 'active',
    PendingApproval: 'pending_approval',
    Blocked: 'blocked',
    Suspended: 'suspended'
} as const;
export type GlobalMembershipItemStatusEnum = typeof GlobalMembershipItemStatusEnum[keyof typeof GlobalMembershipItemStatusEnum];


/**
 * Check if a given object implements the GlobalMembershipItem interface.
 */
export function instanceOfGlobalMembershipItem(value: object): value is GlobalMembershipItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GlobalMembershipItemFromJSON(json: any): GlobalMembershipItem {
    return GlobalMembershipItemFromJSONTyped(json, false);
}

export function GlobalMembershipItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalMembershipItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organization_id'],
        'organizationSlug': json['organization_slug'] == null ? undefined : json['organization_slug'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'appUserId': json['app_user_id'],
        'userDisplayName': json['user_display_name'] == null ? undefined : json['user_display_name'],
        'status': json['status'],
        'sourceProvider': json['source_provider'] == null ? undefined : json['source_provider'],
        'providerOrganizationKey': json['provider_organization_key'] == null ? undefined : json['provider_organization_key'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function GlobalMembershipItemToJSON(json: any): GlobalMembershipItem {
    return GlobalMembershipItemToJSONTyped(json, false);
}

export function GlobalMembershipItemToJSONTyped(value?: GlobalMembershipItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organizationId'],
        'organization_slug': value['organizationSlug'],
        'organization_name': value['organizationName'],
        'app_user_id': value['appUserId'],
        'user_display_name': value['userDisplayName'],
        'status': value['status'],
        'source_provider': value['sourceProvider'],
        'provider_organization_key': value['providerOrganizationKey'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

