/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupListItem } from './GroupListItem';
import {
    GroupListItemFromJSON,
    GroupListItemFromJSONTyped,
    GroupListItemToJSON,
    GroupListItemToJSONTyped,
} from './GroupListItem';

/**
 * 
 * @export
 * @interface GroupDetailEnvelope
 */
export interface GroupDetailEnvelope {
    /**
     * 
     * @type {GroupListItem}
     * @memberof GroupDetailEnvelope
     */
    group: GroupListItem;
}

/**
 * Check if a given object implements the GroupDetailEnvelope interface.
 */
export function instanceOfGroupDetailEnvelope(value: object): value is GroupDetailEnvelope {
    if (!('group' in value) || value['group'] === undefined) return false;
    return true;
}

export function GroupDetailEnvelopeFromJSON(json: any): GroupDetailEnvelope {
    return GroupDetailEnvelopeFromJSONTyped(json, false);
}

export function GroupDetailEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDetailEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'group': GroupListItemFromJSON(json['group']),
    };
}

export function GroupDetailEnvelopeToJSON(json: any): GroupDetailEnvelope {
    return GroupDetailEnvelopeToJSONTyped(json, false);
}

export function GroupDetailEnvelopeToJSONTyped(value?: GroupDetailEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': GroupListItemToJSON(value['group']),
    };
}

