/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupRolesResult
 */
export interface GroupRolesResult {
    /**
     * 
     * @type {boolean}
     * @memberof GroupRolesResult
     */
    ok: GroupRolesResultOkEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupRolesResult
     */
    roleIds: Array<string>;
}


/**
 * @export
 */
export const GroupRolesResultOkEnum = {
    True: true
} as const;
export type GroupRolesResultOkEnum = typeof GroupRolesResultOkEnum[keyof typeof GroupRolesResultOkEnum];


/**
 * Check if a given object implements the GroupRolesResult interface.
 */
export function instanceOfGroupRolesResult(value: object): value is GroupRolesResult {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('roleIds' in value) || value['roleIds'] === undefined) return false;
    return true;
}

export function GroupRolesResultFromJSON(json: any): GroupRolesResult {
    return GroupRolesResultFromJSONTyped(json, false);
}

export function GroupRolesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRolesResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'roleIds': json['roleIds'],
    };
}

export function GroupRolesResultToJSON(json: any): GroupRolesResult {
    return GroupRolesResultToJSONTyped(json, false);
}

export function GroupRolesResultToJSONTyped(value?: GroupRolesResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'roleIds': value['roleIds'],
    };
}

