/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupMemberItem } from './GroupMemberItem';
import {
    GroupMemberItemFromJSON,
    GroupMemberItemFromJSONTyped,
    GroupMemberItemToJSON,
    GroupMemberItemToJSONTyped,
} from './GroupMemberItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface GroupMemberList
 */
export interface GroupMemberList {
    /**
     * 
     * @type {Array<GroupMemberItem>}
     * @memberof GroupMemberList
     */
    items: Array<GroupMemberItem>;
    /**
     * 
     * @type {number}
     * @memberof GroupMemberList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GroupMemberList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof GroupMemberList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof GroupMemberList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the GroupMemberList interface.
 */
export function instanceOfGroupMemberList(value: object): value is GroupMemberList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function GroupMemberListFromJSON(json: any): GroupMemberList {
    return GroupMemberListFromJSONTyped(json, false);
}

export function GroupMemberListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMemberList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GroupMemberItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function GroupMemberListToJSON(json: any): GroupMemberList {
    return GroupMemberListToJSONTyped(json, false);
}

export function GroupMemberListToJSONTyped(value?: GroupMemberList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GroupMemberItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

