/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupRolesRolesInner } from './GroupRolesRolesInner';
import {
    GroupRolesRolesInnerFromJSON,
    GroupRolesRolesInnerFromJSONTyped,
    GroupRolesRolesInnerToJSON,
    GroupRolesRolesInnerToJSONTyped,
} from './GroupRolesRolesInner';

/**
 * 
 * @export
 * @interface GroupRoles
 */
export interface GroupRoles {
    /**
     * 
     * @type {Array<GroupRolesRolesInner>}
     * @memberof GroupRoles
     */
    roles: Array<GroupRolesRolesInner>;
}

/**
 * Check if a given object implements the GroupRoles interface.
 */
export function instanceOfGroupRoles(value: object): value is GroupRoles {
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function GroupRolesFromJSON(json: any): GroupRoles {
    return GroupRolesFromJSONTyped(json, false);
}

export function GroupRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRoles {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': ((json['roles'] as Array<any>).map(GroupRolesRolesInnerFromJSON)),
    };
}

export function GroupRolesToJSON(json: any): GroupRoles {
    return GroupRolesToJSONTyped(json, false);
}

export function GroupRolesToJSONTyped(value?: GroupRoles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': ((value['roles'] as Array<any>).map(GroupRolesRolesInnerToJSON)),
    };
}

