/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupMemberItem
 */
export interface GroupMemberItem {
    /**
     * 
     * @type {string}
     * @memberof GroupMemberItem
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMemberItem
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMemberItem
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupMemberItem
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof GroupMemberItem
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the GroupMemberItem interface.
 */
export function instanceOfGroupMemberItem(value: object): value is GroupMemberItem {
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    return true;
}

export function GroupMemberItemFromJSON(json: any): GroupMemberItem {
    return GroupMemberItemFromJSONTyped(json, false);
}

export function GroupMemberItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMemberItem {
    if (json == null) {
        return json;
    }
    return {
        
        'appUserId': json['app_user_id'],
        'primaryEmail': json['primary_email'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function GroupMemberItemToJSON(json: any): GroupMemberItem {
    return GroupMemberItemToJSONTyped(json, false);
}

export function GroupMemberItemToJSONTyped(value?: GroupMemberItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_user_id': value['appUserId'],
        'primary_email': value['primaryEmail'],
        'display_name': value['displayName'],
        'status': value['status'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

