/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdCreated
 */
export interface IdCreated {
    /**
     * 
     * @type {boolean}
     * @memberof IdCreated
     */
    ok: IdCreatedOkEnum;
    /**
     * 
     * @type {string}
     * @memberof IdCreated
     */
    id: string;
}


/**
 * @export
 */
export const IdCreatedOkEnum = {
    True: true
} as const;
export type IdCreatedOkEnum = typeof IdCreatedOkEnum[keyof typeof IdCreatedOkEnum];


/**
 * Check if a given object implements the IdCreated interface.
 */
export function instanceOfIdCreated(value: object): value is IdCreated {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function IdCreatedFromJSON(json: any): IdCreated {
    return IdCreatedFromJSONTyped(json, false);
}

export function IdCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'id': json['id'],
    };
}

export function IdCreatedToJSON(json: any): IdCreated {
    return IdCreatedToJSONTyped(json, false);
}

export function IdCreatedToJSONTyped(value?: IdCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'id': value['id'],
    };
}

