/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationResent
 */
export interface InvitationResent {
    /**
     * 
     * @type {boolean}
     * @memberof InvitationResent
     */
    ok: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InvitationResent
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the InvitationResent interface.
 */
export function instanceOfInvitationResent(value: object): value is InvitationResent {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function InvitationResentFromJSON(json: any): InvitationResent {
    return InvitationResentFromJSONTyped(json, false);
}

export function InvitationResentFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationResent {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function InvitationResentToJSON(json: any): InvitationResent {
    return InvitationResentToJSONTyped(json, false);
}

export function InvitationResentToJSONTyped(value?: InvitationResent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'expiresAt': ((value['expiresAt']).toISOString()),
    };
}

