/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyCreated
 */
export interface KeyCreated {
    /**
     * 
     * @type {boolean}
     * @memberof KeyCreated
     */
    ok: KeyCreatedOkEnum;
    /**
     * 
     * @type {string}
     * @memberof KeyCreated
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof KeyCreated
     */
    key: string;
}


/**
 * @export
 */
export const KeyCreatedOkEnum = {
    True: true
} as const;
export type KeyCreatedOkEnum = typeof KeyCreatedOkEnum[keyof typeof KeyCreatedOkEnum];


/**
 * Check if a given object implements the KeyCreated interface.
 */
export function instanceOfKeyCreated(value: object): value is KeyCreated {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function KeyCreatedFromJSON(json: any): KeyCreated {
    return KeyCreatedFromJSONTyped(json, false);
}

export function KeyCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'id': json['id'],
        'key': json['key'],
    };
}

export function KeyCreatedToJSON(json: any): KeyCreated {
    return KeyCreatedToJSONTyped(json, false);
}

export function KeyCreatedToJSONTyped(value?: KeyCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'id': value['id'],
        'key': value['key'],
    };
}

