/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpAgentRevoked
 */
export interface McpAgentRevoked {
    /**
     * 
     * @type {boolean}
     * @memberof McpAgentRevoked
     */
    ok: McpAgentRevokedOkEnum;
    /**
     * Present (true) when the client was not active any more — a no-op.
     * @type {boolean}
     * @memberof McpAgentRevoked
     */
    alreadyRevoked?: boolean;
}


/**
 * @export
 */
export const McpAgentRevokedOkEnum = {
    True: true
} as const;
export type McpAgentRevokedOkEnum = typeof McpAgentRevokedOkEnum[keyof typeof McpAgentRevokedOkEnum];


/**
 * Check if a given object implements the McpAgentRevoked interface.
 */
export function instanceOfMcpAgentRevoked(value: object): value is McpAgentRevoked {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function McpAgentRevokedFromJSON(json: any): McpAgentRevoked {
    return McpAgentRevokedFromJSONTyped(json, false);
}

export function McpAgentRevokedFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpAgentRevoked {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'alreadyRevoked': json['alreadyRevoked'] == null ? undefined : json['alreadyRevoked'],
    };
}

export function McpAgentRevokedToJSON(json: any): McpAgentRevoked {
    return McpAgentRevokedToJSONTyped(json, false);
}

export function McpAgentRevokedToJSONTyped(value?: McpAgentRevoked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'alreadyRevoked': value['alreadyRevoked'],
    };
}

