/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpAgentItem
 */
export interface McpAgentItem {
    /**
     * OAuth-client row id — the `{id}` of the agent operations.
     * @type {string}
     * @memberof McpAgentItem
     */
    clientRowId: string;
    /**
     * Public OAuth `client_id`.
     * @type {string}
     * @memberof McpAgentItem
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof McpAgentItem
     */
    name: string;
    /**
     * Scope ceiling (effective = scopes ∩ permissions).
     * @type {Array<string>}
     * @memberof McpAgentItem
     */
    scopes: Array<string>;
    /**
     * Raw `app_oauth_clients.status`.
     * @type {string}
     * @memberof McpAgentItem
     */
    clientStatus: string;
    /**
     * The agent's service account.
     * @type {string}
     * @memberof McpAgentItem
     */
    appUserId: string;
    /**
     * Raw `app_users.status` of the service account.
     * @type {string}
     * @memberof McpAgentItem
     */
    userStatus: string;
    /**
     * 
     * @type {string}
     * @memberof McpAgentItem
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof McpAgentItem
     */
    organizationId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof McpAgentItem
     */
    createdAt: Date;
    /**
     * Derived lifecycle status (pending ⇒ awaiting approval; revoked ⇒ client inactive).
     * @type {string}
     * @memberof McpAgentItem
     */
    status: McpAgentItemStatusEnum;
}


/**
 * @export
 */
export const McpAgentItemStatusEnum = {
    Pending: 'pending',
    Active: 'active',
    Revoked: 'revoked'
} as const;
export type McpAgentItemStatusEnum = typeof McpAgentItemStatusEnum[keyof typeof McpAgentItemStatusEnum];


/**
 * Check if a given object implements the McpAgentItem interface.
 */
export function instanceOfMcpAgentItem(value: object): value is McpAgentItem {
    if (!('clientRowId' in value) || value['clientRowId'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('clientStatus' in value) || value['clientStatus'] === undefined) return false;
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function McpAgentItemFromJSON(json: any): McpAgentItem {
    return McpAgentItemFromJSONTyped(json, false);
}

export function McpAgentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpAgentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'clientRowId': json['clientRowId'],
        'clientId': json['clientId'],
        'name': json['name'],
        'scopes': json['scopes'],
        'clientStatus': json['clientStatus'],
        'appUserId': json['appUserId'],
        'userStatus': json['userStatus'],
        'email': json['email'],
        'organizationId': json['organizationId'],
        'createdAt': (new Date(json['createdAt'])),
        'status': json['status'],
    };
}

export function McpAgentItemToJSON(json: any): McpAgentItem {
    return McpAgentItemToJSONTyped(json, false);
}

export function McpAgentItemToJSONTyped(value?: McpAgentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientRowId': value['clientRowId'],
        'clientId': value['clientId'],
        'name': value['name'],
        'scopes': value['scopes'],
        'clientStatus': value['clientStatus'],
        'appUserId': value['appUserId'],
        'userStatus': value['userStatus'],
        'email': value['email'],
        'organizationId': value['organizationId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'status': value['status'],
    };
}

