/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ok
 */
export interface Ok {
    /**
     * 
     * @type {boolean}
     * @memberof Ok
     */
    ok: OkOkEnum;
}


/**
 * @export
 */
export const OkOkEnum = {
    True: true
} as const;
export type OkOkEnum = typeof OkOkEnum[keyof typeof OkOkEnum];


/**
 * Check if a given object implements the Ok interface.
 */
export function instanceOfOk(value: object): value is Ok {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function OkFromJSON(json: any): Ok {
    return OkFromJSONTyped(json, false);
}

export function OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ok {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
    };
}

export function OkToJSON(json: any): Ok {
    return OkToJSONTyped(json, false);
}

export function OkToJSONTyped(value?: Ok | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

