/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OkStatus
 */
export interface OkStatus {
    /**
     * 
     * @type {boolean}
     * @memberof OkStatus
     */
    ok: OkStatusOkEnum;
    /**
     * 
     * @type {string}
     * @memberof OkStatus
     */
    status: string;
}


/**
 * @export
 */
export const OkStatusOkEnum = {
    True: true
} as const;
export type OkStatusOkEnum = typeof OkStatusOkEnum[keyof typeof OkStatusOkEnum];


/**
 * Check if a given object implements the OkStatus interface.
 */
export function instanceOfOkStatus(value: object): value is OkStatus {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OkStatusFromJSON(json: any): OkStatus {
    return OkStatusFromJSONTyped(json, false);
}

export function OkStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'status': json['status'],
    };
}

export function OkStatusToJSON(json: any): OkStatus {
    return OkStatusToJSONTyped(json, false);
}

export function OkStatusToJSONTyped(value?: OkStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'status': value['status'],
    };
}

