/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationListItem
 */
export interface OrganizationListItem {
    /**
     * 
     * @type {string}
     * @memberof OrganizationListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListItem
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListItem
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationListItem
     */
    isDefault?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationListItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganizationListItem
     */
    memberCount?: number;
}

/**
 * Check if a given object implements the OrganizationListItem interface.
 */
export function instanceOfOrganizationListItem(value: object): value is OrganizationListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationListItemFromJSON(json: any): OrganizationListItem {
    return OrganizationListItemFromJSONTyped(json, false);
}

export function OrganizationListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'memberCount': json['member_count'] == null ? undefined : json['member_count'],
    };
}

export function OrganizationListItemToJSON(json: any): OrganizationListItem {
    return OrganizationListItemToJSONTyped(json, false);
}

export function OrganizationListItemToJSONTyped(value?: OrganizationListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'status': value['status'],
        'is_default': value['isDefault'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'member_count': value['memberCount'],
    };
}

