/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgMemberItem
 */
export interface OrgMemberItem {
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    userDisplayName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    status: OrgMemberItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    sourceProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrgMemberItem
     */
    providerOrganizationKey?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrgMemberItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrgMemberItem
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const OrgMemberItemStatusEnum = {
    Active: 'active',
    PendingApproval: 'pending_approval',
    Blocked: 'blocked',
    Suspended: 'suspended'
} as const;
export type OrgMemberItemStatusEnum = typeof OrgMemberItemStatusEnum[keyof typeof OrgMemberItemStatusEnum];


/**
 * Check if a given object implements the OrgMemberItem interface.
 */
export function instanceOfOrgMemberItem(value: object): value is OrgMemberItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrgMemberItemFromJSON(json: any): OrgMemberItem {
    return OrgMemberItemFromJSONTyped(json, false);
}

export function OrgMemberItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgMemberItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appUserId': json['app_user_id'],
        'userDisplayName': json['user_display_name'] == null ? undefined : json['user_display_name'],
        'status': json['status'],
        'sourceProvider': json['source_provider'] == null ? undefined : json['source_provider'],
        'providerOrganizationKey': json['provider_organization_key'] == null ? undefined : json['provider_organization_key'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function OrgMemberItemToJSON(json: any): OrgMemberItem {
    return OrgMemberItemToJSONTyped(json, false);
}

export function OrgMemberItemToJSONTyped(value?: OrgMemberItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'app_user_id': value['appUserId'],
        'user_display_name': value['userDisplayName'],
        'status': value['status'],
        'source_provider': value['sourceProvider'],
        'provider_organization_key': value['providerOrganizationKey'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

