/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One outbox row with its rendered bodies. Bodies are the REDACTED rendering stored at insert time: one-time reset / verification / invitation tokens read `[redacted]`.
 * @export
 * @interface OutboxDetail
 */
export interface OutboxDetail {
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    organizationSlug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    organizationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    templateKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    toEmail: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    fromEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    status: OutboxDetailStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    providerMessageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    relatedBetterAuthUserId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OutboxDetail
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OutboxDetail
     */
    sentAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    bodyHtml: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxDetail
     */
    bodyText?: string | null;
}


/**
 * @export
 */
export const OutboxDetailStatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Failed: 'failed',
    Logged: 'logged'
} as const;
export type OutboxDetailStatusEnum = typeof OutboxDetailStatusEnum[keyof typeof OutboxDetailStatusEnum];


/**
 * Check if a given object implements the OutboxDetail interface.
 */
export function instanceOfOutboxDetail(value: object): value is OutboxDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('toEmail' in value) || value['toEmail'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('bodyHtml' in value) || value['bodyHtml'] === undefined) return false;
    return true;
}

export function OutboxDetailFromJSON(json: any): OutboxDetail {
    return OutboxDetailFromJSONTyped(json, false);
}

export function OutboxDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboxDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'organizationSlug': json['organization_slug'] == null ? undefined : json['organization_slug'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'templateKey': json['template_key'] == null ? undefined : json['template_key'],
        'toEmail': json['to_email'],
        'fromEmail': json['from_email'] == null ? undefined : json['from_email'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'status': json['status'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerMessageId': json['provider_message_id'] == null ? undefined : json['provider_message_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'relatedBetterAuthUserId': json['related_better_auth_user_id'] == null ? undefined : json['related_better_auth_user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'sentAt': json['sent_at'] == null ? undefined : (new Date(json['sent_at'])),
        'bodyHtml': json['body_html'],
        'bodyText': json['body_text'] == null ? undefined : json['body_text'],
    };
}

export function OutboxDetailToJSON(json: any): OutboxDetail {
    return OutboxDetailToJSONTyped(json, false);
}

export function OutboxDetailToJSONTyped(value?: OutboxDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organizationId'],
        'organization_slug': value['organizationSlug'],
        'organization_name': value['organizationName'],
        'template_key': value['templateKey'],
        'to_email': value['toEmail'],
        'from_email': value['fromEmail'],
        'subject': value['subject'],
        'status': value['status'],
        'provider': value['provider'],
        'provider_message_id': value['providerMessageId'],
        'error': value['error'],
        'related_better_auth_user_id': value['relatedBetterAuthUserId'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'sent_at': value['sentAt'] == null ? undefined : ((value['sentAt'] as any).toISOString()),
        'body_html': value['bodyHtml'],
        'body_text': value['bodyText'],
    };
}

