/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutboxItem } from './OutboxItem';
import {
    OutboxItemFromJSON,
    OutboxItemFromJSONTyped,
    OutboxItemToJSON,
    OutboxItemToJSONTyped,
} from './OutboxItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface OutboxList
 */
export interface OutboxList {
    /**
     * 
     * @type {Array<OutboxItem>}
     * @memberof OutboxList
     */
    items: Array<OutboxItem>;
    /**
     * 
     * @type {number}
     * @memberof OutboxList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof OutboxList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof OutboxList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof OutboxList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the OutboxList interface.
 */
export function instanceOfOutboxList(value: object): value is OutboxList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function OutboxListFromJSON(json: any): OutboxList {
    return OutboxListFromJSONTyped(json, false);
}

export function OutboxListFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboxList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OutboxItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function OutboxListToJSON(json: any): OutboxList {
    return OutboxListToJSONTyped(json, false);
}

export function OutboxListToJSONTyped(value?: OutboxList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OutboxItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

