/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutboxItem
 */
export interface OutboxItem {
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    organizationSlug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    organizationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    templateKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    toEmail: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    fromEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    status: OutboxItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    providerMessageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutboxItem
     */
    relatedBetterAuthUserId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OutboxItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OutboxItem
     */
    sentAt?: Date | null;
}


/**
 * @export
 */
export const OutboxItemStatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Failed: 'failed',
    Logged: 'logged'
} as const;
export type OutboxItemStatusEnum = typeof OutboxItemStatusEnum[keyof typeof OutboxItemStatusEnum];


/**
 * Check if a given object implements the OutboxItem interface.
 */
export function instanceOfOutboxItem(value: object): value is OutboxItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('toEmail' in value) || value['toEmail'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OutboxItemFromJSON(json: any): OutboxItem {
    return OutboxItemFromJSONTyped(json, false);
}

export function OutboxItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboxItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'organizationSlug': json['organization_slug'] == null ? undefined : json['organization_slug'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'templateKey': json['template_key'] == null ? undefined : json['template_key'],
        'toEmail': json['to_email'],
        'fromEmail': json['from_email'] == null ? undefined : json['from_email'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'status': json['status'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerMessageId': json['provider_message_id'] == null ? undefined : json['provider_message_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'relatedBetterAuthUserId': json['related_better_auth_user_id'] == null ? undefined : json['related_better_auth_user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'sentAt': json['sent_at'] == null ? undefined : (new Date(json['sent_at'])),
    };
}

export function OutboxItemToJSON(json: any): OutboxItem {
    return OutboxItemToJSONTyped(json, false);
}

export function OutboxItemToJSONTyped(value?: OutboxItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organizationId'],
        'organization_slug': value['organizationSlug'],
        'organization_name': value['organizationName'],
        'template_key': value['templateKey'],
        'to_email': value['toEmail'],
        'from_email': value['fromEmail'],
        'subject': value['subject'],
        'status': value['status'],
        'provider': value['provider'],
        'provider_message_id': value['providerMessageId'],
        'error': value['error'],
        'related_better_auth_user_id': value['relatedBetterAuthUserId'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'sent_at': value['sentAt'] == null ? undefined : ((value['sentAt'] as any).toISOString()),
    };
}

