/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionsResult
 */
export interface PermissionsResult {
    /**
     * 
     * @type {boolean}
     * @memberof PermissionsResult
     */
    ok: PermissionsResultOkEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionsResult
     */
    permissions: Array<string>;
}


/**
 * @export
 */
export const PermissionsResultOkEnum = {
    True: true
} as const;
export type PermissionsResultOkEnum = typeof PermissionsResultOkEnum[keyof typeof PermissionsResultOkEnum];


/**
 * Check if a given object implements the PermissionsResult interface.
 */
export function instanceOfPermissionsResult(value: object): value is PermissionsResult {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function PermissionsResultFromJSON(json: any): PermissionsResult {
    return PermissionsResultFromJSONTyped(json, false);
}

export function PermissionsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'permissions': json['permissions'],
    };
}

export function PermissionsResultToJSON(json: any): PermissionsResult {
    return PermissionsResultToJSONTyped(json, false);
}

export function PermissionsResultToJSONTyped(value?: PermissionsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'permissions': value['permissions'],
    };
}

