/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionsList
 */
export interface PermissionsList {
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionsList
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the PermissionsList interface.
 */
export function instanceOfPermissionsList(value: object): value is PermissionsList {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function PermissionsListFromJSON(json: any): PermissionsList {
    return PermissionsListFromJSONTyped(json, false);
}

export function PermissionsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionsList {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': json['permissions'],
    };
}

export function PermissionsListToJSON(json: any): PermissionsList {
    return PermissionsListToJSONTyped(json, false);
}

export function PermissionsListToJSONTyped(value?: PermissionsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': value['permissions'],
    };
}

