/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionListItem } from './PermissionListItem';
import {
    PermissionListItemFromJSON,
    PermissionListItemFromJSONTyped,
    PermissionListItemToJSON,
    PermissionListItemToJSONTyped,
} from './PermissionListItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface PermissionList
 */
export interface PermissionList {
    /**
     * 
     * @type {Array<PermissionListItem>}
     * @memberof PermissionList
     */
    items: Array<PermissionListItem>;
    /**
     * 
     * @type {number}
     * @memberof PermissionList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PermissionList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof PermissionList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the PermissionList interface.
 */
export function instanceOfPermissionList(value: object): value is PermissionList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PermissionListFromJSON(json: any): PermissionList {
    return PermissionListFromJSONTyped(json, false);
}

export function PermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PermissionListItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function PermissionListToJSON(json: any): PermissionList {
    return PermissionListToJSONTyped(json, false);
}

export function PermissionListToJSONTyped(value?: PermissionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PermissionListItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

