/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RateLimitedError
 */
export interface RateLimitedError {
    /**
     * Machine-readable code.
     * @type {string}
     * @memberof RateLimitedError
     */
    error: string;
    /**
     * i18n message key.
     * @type {string}
     * @memberof RateLimitedError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof RateLimitedError
     */
    requestId: string;
    /**
     * Seconds until the bucket refills enough to retry.
     * @type {number}
     * @memberof RateLimitedError
     */
    retryAfter: number;
}

/**
 * Check if a given object implements the RateLimitedError interface.
 */
export function instanceOfRateLimitedError(value: object): value is RateLimitedError {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('retryAfter' in value) || value['retryAfter'] === undefined) return false;
    return true;
}

export function RateLimitedErrorFromJSON(json: any): RateLimitedError {
    return RateLimitedErrorFromJSONTyped(json, false);
}

export function RateLimitedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateLimitedError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'message': json['message'],
        'requestId': json['requestId'],
        'retryAfter': json['retryAfter'],
    };
}

export function RateLimitedErrorToJSON(json: any): RateLimitedError {
    return RateLimitedErrorToJSONTyped(json, false);
}

export function RateLimitedErrorToJSONTyped(value?: RateLimitedError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
        'requestId': value['requestId'],
        'retryAfter': value['retryAfter'],
    };
}

