/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReasonRequest
 */
export interface ReasonRequest {
    /**
     * 
     * @type {string}
     * @memberof ReasonRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the ReasonRequest interface.
 */
export function instanceOfReasonRequest(value: object): value is ReasonRequest {
    return true;
}

export function ReasonRequestFromJSON(json: any): ReasonRequest {
    return ReasonRequestFromJSONTyped(json, false);
}

export function ReasonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasonRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function ReasonRequestToJSON(json: any): ReasonRequest {
    return ReasonRequestToJSONTyped(json, false);
}

export function ReasonRequestToJSONTyped(value?: ReasonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

