/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleDetail } from './RoleDetail';
import {
    RoleDetailFromJSON,
    RoleDetailFromJSONTyped,
    RoleDetailToJSON,
    RoleDetailToJSONTyped,
} from './RoleDetail';

/**
 * 
 * @export
 * @interface RoleDetailEnvelope
 */
export interface RoleDetailEnvelope {
    /**
     * 
     * @type {RoleDetail}
     * @memberof RoleDetailEnvelope
     */
    role: RoleDetail;
}

/**
 * Check if a given object implements the RoleDetailEnvelope interface.
 */
export function instanceOfRoleDetailEnvelope(value: object): value is RoleDetailEnvelope {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RoleDetailEnvelopeFromJSON(json: any): RoleDetailEnvelope {
    return RoleDetailEnvelopeFromJSONTyped(json, false);
}

export function RoleDetailEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleDetailEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'role': RoleDetailFromJSON(json['role']),
    };
}

export function RoleDetailEnvelopeToJSON(json: any): RoleDetailEnvelope {
    return RoleDetailEnvelopeToJSONTyped(json, false);
}

export function RoleDetailEnvelopeToJSONTyped(value?: RoleDetailEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': RoleDetailToJSON(value['role']),
    };
}

