/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleListItem } from './RoleListItem';
import {
    RoleListItemFromJSON,
    RoleListItemFromJSONTyped,
    RoleListItemToJSON,
    RoleListItemToJSONTyped,
} from './RoleListItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface RoleList
 */
export interface RoleList {
    /**
     * 
     * @type {Array<RoleListItem>}
     * @memberof RoleList
     */
    items: Array<RoleListItem>;
    /**
     * 
     * @type {number}
     * @memberof RoleList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof RoleList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof RoleList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof RoleList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the RoleList interface.
 */
export function instanceOfRoleList(value: object): value is RoleList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function RoleListFromJSON(json: any): RoleList {
    return RoleListFromJSONTyped(json, false);
}

export function RoleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(RoleListItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function RoleListToJSON(json: any): RoleList {
    return RoleListToJSONTyped(json, false);
}

export function RoleListToJSONTyped(value?: RoleList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(RoleListItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

