/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleMemberItem
 */
export interface RoleMemberItem {
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    appUserId: string;
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleMemberItem
     */
    organizationName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleMemberItem
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the RoleMemberItem interface.
 */
export function instanceOfRoleMemberItem(value: object): value is RoleMemberItem {
    if (!('appUserId' in value) || value['appUserId'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    return true;
}

export function RoleMemberItemFromJSON(json: any): RoleMemberItem {
    return RoleMemberItemFromJSONTyped(json, false);
}

export function RoleMemberItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleMemberItem {
    if (json == null) {
        return json;
    }
    return {
        
        'appUserId': json['app_user_id'],
        'primaryEmail': json['primary_email'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'status': json['status'] == null ? undefined : json['status'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function RoleMemberItemToJSON(json: any): RoleMemberItem {
    return RoleMemberItemToJSONTyped(json, false);
}

export function RoleMemberItemToJSONTyped(value?: RoleMemberItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_user_id': value['appUserId'],
        'primary_email': value['primaryEmail'],
        'display_name': value['displayName'],
        'status': value['status'],
        'organization_id': value['organizationId'],
        'organization_name': value['organizationName'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

