/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleListItem
 */
export interface RoleListItem {
    /**
     * 
     * @type {string}
     * @memberof RoleListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleListItem
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleListItem
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof RoleListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleListItem
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleListItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof RoleListItem
     */
    permissionCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RoleListItem
     */
    memberCount?: number;
}

/**
 * Check if a given object implements the RoleListItem interface.
 */
export function instanceOfRoleListItem(value: object): value is RoleListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoleListItemFromJSON(json: any): RoleListItem {
    return RoleListItemFromJSONTyped(json, false);
}

export function RoleListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'key': json['key'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'permissionCount': json['permission_count'] == null ? undefined : json['permission_count'],
        'memberCount': json['member_count'] == null ? undefined : json['member_count'],
    };
}

export function RoleListItemToJSON(json: any): RoleListItem {
    return RoleListItemToJSONTyped(json, false);
}

export function RoleListItemToJSONTyped(value?: RoleListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organizationId'],
        'key': value['key'],
        'name': value['name'],
        'description': value['description'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'permission_count': value['permissionCount'],
        'member_count': value['memberCount'],
    };
}

