/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendTestEmailResult
 */
export interface SendTestEmailResult {
    /**
     * 
     * @type {boolean}
     * @memberof SendTestEmailResult
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailResult
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailResult
     */
    outboxId: string;
}

/**
 * Check if a given object implements the SendTestEmailResult interface.
 */
export function instanceOfSendTestEmailResult(value: object): value is SendTestEmailResult {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('outboxId' in value) || value['outboxId'] === undefined) return false;
    return true;
}

export function SendTestEmailResultFromJSON(json: any): SendTestEmailResult {
    return SendTestEmailResultFromJSONTyped(json, false);
}

export function SendTestEmailResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendTestEmailResult {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'status': json['status'],
        'outboxId': json['outboxId'],
    };
}

export function SendTestEmailResultToJSON(json: any): SendTestEmailResult {
    return SendTestEmailResultToJSONTyped(json, false);
}

export function SendTestEmailResultToJSONTyped(value?: SendTestEmailResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'status': value['status'],
        'outboxId': value['outboxId'],
    };
}

