/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordRequestOneOf
 */
export interface SetPasswordRequestOneOf {
    /**
     * 
     * @type {any}
     * @memberof SetPasswordRequestOneOf
     */
    mode: any | null;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordRequestOneOf
     */
    password: string;
}

/**
 * Check if a given object implements the SetPasswordRequestOneOf interface.
 */
export function instanceOfSetPasswordRequestOneOf(value: object): value is SetPasswordRequestOneOf {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SetPasswordRequestOneOfFromJSON(json: any): SetPasswordRequestOneOf {
    return SetPasswordRequestOneOfFromJSONTyped(json, false);
}

export function SetPasswordRequestOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordRequestOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'password': json['password'],
    };
}

export function SetPasswordRequestOneOfToJSON(json: any): SetPasswordRequestOneOf {
    return SetPasswordRequestOneOfToJSONTyped(json, false);
}

export function SetPasswordRequestOneOfToJSONTyped(value?: SetPasswordRequestOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'password': value['password'],
    };
}

