/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SetPasswordRequestOneOf } from './SetPasswordRequestOneOf';
import {
    instanceOfSetPasswordRequestOneOf,
    SetPasswordRequestOneOfFromJSON,
    SetPasswordRequestOneOfFromJSONTyped,
    SetPasswordRequestOneOfToJSON,
} from './SetPasswordRequestOneOf';
import type { SetPasswordRequestOneOf1 } from './SetPasswordRequestOneOf1';
import {
    instanceOfSetPasswordRequestOneOf1,
    SetPasswordRequestOneOf1FromJSON,
    SetPasswordRequestOneOf1FromJSONTyped,
    SetPasswordRequestOneOf1ToJSON,
} from './SetPasswordRequestOneOf1';

/**
 * @type SetPasswordRequest
 * 
 * @export
 */
export type SetPasswordRequest = SetPasswordRequestOneOf | SetPasswordRequestOneOf1;

export function SetPasswordRequestFromJSON(json: any): SetPasswordRequest {
    return SetPasswordRequestFromJSONTyped(json, false);
}

export function SetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordRequest {
    if (json == null) {
        return json;
    }
    if (instanceOfSetPasswordRequestOneOf(json)) {
        return SetPasswordRequestOneOfFromJSONTyped(json, true);
    }
    if (instanceOfSetPasswordRequestOneOf1(json)) {
        return SetPasswordRequestOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function SetPasswordRequestToJSON(json: any): any {
    return SetPasswordRequestToJSONTyped(json, false);
}

export function SetPasswordRequestToJSONTyped(value?: SetPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfSetPasswordRequestOneOf(value)) {
        return SetPasswordRequestOneOfToJSON(value as SetPasswordRequestOneOf);
    }
    if (instanceOfSetPasswordRequestOneOf1(value)) {
        return SetPasswordRequestOneOf1ToJSON(value as SetPasswordRequestOneOf1);
    }

    return {};
}

