/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetRoleRequest
 */
export interface SetRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof SetRoleRequest
     */
    role: SetRoleRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof SetRoleRequest
     */
    reason?: string;
}


/**
 * @export
 */
export const SetRoleRequestRoleEnum = {
    Admin: 'admin',
    User: 'user'
} as const;
export type SetRoleRequestRoleEnum = typeof SetRoleRequestRoleEnum[keyof typeof SetRoleRequestRoleEnum];


/**
 * Check if a given object implements the SetRoleRequest interface.
 */
export function instanceOfSetRoleRequest(value: object): value is SetRoleRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function SetRoleRequestFromJSON(json: any): SetRoleRequest {
    return SetRoleRequestFromJSONTyped(json, false);
}

export function SetRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function SetRoleRequestToJSON(json: any): SetRoleRequest {
    return SetRoleRequestToJSONTyped(json, false);
}

export function SetRoleRequestToJSONTyped(value?: SetRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'reason': value['reason'],
    };
}

