/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetUserPlatformRole200Response
 */
export interface SetUserPlatformRole200Response {
    /**
     * 
     * @type {any}
     * @memberof SetUserPlatformRole200Response
     */
    ok?: any | null;
    /**
     * 
     * @type {string}
     * @memberof SetUserPlatformRole200Response
     */
    role?: string;
}

/**
 * Check if a given object implements the SetUserPlatformRole200Response interface.
 */
export function instanceOfSetUserPlatformRole200Response(value: object): value is SetUserPlatformRole200Response {
    return true;
}

export function SetUserPlatformRole200ResponseFromJSON(json: any): SetUserPlatformRole200Response {
    return SetUserPlatformRole200ResponseFromJSONTyped(json, false);
}

export function SetUserPlatformRole200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserPlatformRole200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function SetUserPlatformRole200ResponseToJSON(json: any): SetUserPlatformRole200Response {
    return SetUserPlatformRole200ResponseToJSONTyped(json, false);
}

export function SetUserPlatformRole200ResponseToJSONTyped(value?: SetUserPlatformRole200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'role': value['role'],
    };
}

