/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A COMPLETE policy — there is no partial update; PATCH creates or replaces the row.
 * @export
 * @interface UpdateAuthPolicyRequest
 */
export interface UpdateAuthPolicyRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAuthPolicyRequest
     */
    requireEmailVerification: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthPolicyRequest
     */
    signupApprovalMode: UpdateAuthPolicyRequestSignupApprovalModeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAuthPolicyRequest
     */
    allowedAuthMethods: Array<UpdateAuthPolicyRequestAllowedAuthMethodsEnum> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAuthPolicyRequest
     */
    autoApproveEmailDomains: Array<string> | null;
}


/**
 * @export
 */
export const UpdateAuthPolicyRequestSignupApprovalModeEnum = {
    AdminApproval: 'admin_approval',
    AutoActive: 'auto_active',
    InviteOnly: 'invite_only'
} as const;
export type UpdateAuthPolicyRequestSignupApprovalModeEnum = typeof UpdateAuthPolicyRequestSignupApprovalModeEnum[keyof typeof UpdateAuthPolicyRequestSignupApprovalModeEnum];

/**
 * @export
 */
export const UpdateAuthPolicyRequestAllowedAuthMethodsEnum = {
    Email: 'email',
    Google: 'google',
    Microsoft: 'microsoft',
    Github: 'github'
} as const;
export type UpdateAuthPolicyRequestAllowedAuthMethodsEnum = typeof UpdateAuthPolicyRequestAllowedAuthMethodsEnum[keyof typeof UpdateAuthPolicyRequestAllowedAuthMethodsEnum];


/**
 * Check if a given object implements the UpdateAuthPolicyRequest interface.
 */
export function instanceOfUpdateAuthPolicyRequest(value: object): value is UpdateAuthPolicyRequest {
    if (!('requireEmailVerification' in value) || value['requireEmailVerification'] === undefined) return false;
    if (!('signupApprovalMode' in value) || value['signupApprovalMode'] === undefined) return false;
    if (!('allowedAuthMethods' in value) || value['allowedAuthMethods'] === undefined) return false;
    if (!('autoApproveEmailDomains' in value) || value['autoApproveEmailDomains'] === undefined) return false;
    return true;
}

export function UpdateAuthPolicyRequestFromJSON(json: any): UpdateAuthPolicyRequest {
    return UpdateAuthPolicyRequestFromJSONTyped(json, false);
}

export function UpdateAuthPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAuthPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requireEmailVerification': json['requireEmailVerification'],
        'signupApprovalMode': json['signupApprovalMode'],
        'allowedAuthMethods': json['allowedAuthMethods'] == null ? null : json['allowedAuthMethods'],
        'autoApproveEmailDomains': json['autoApproveEmailDomains'] == null ? null : json['autoApproveEmailDomains'],
    };
}

export function UpdateAuthPolicyRequestToJSON(json: any): UpdateAuthPolicyRequest {
    return UpdateAuthPolicyRequestToJSONTyped(json, false);
}

export function UpdateAuthPolicyRequestToJSONTyped(value?: UpdateAuthPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requireEmailVerification': value['requireEmailVerification'],
        'signupApprovalMode': value['signupApprovalMode'],
        'allowedAuthMethods': value['allowedAuthMethods'],
        'autoApproveEmailDomains': value['autoApproveEmailDomains'],
    };
}

