/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePermissionRequest
 */
export interface UpdatePermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePermissionRequest
     */
    description: string | null;
}

/**
 * Check if a given object implements the UpdatePermissionRequest interface.
 */
export function instanceOfUpdatePermissionRequest(value: object): value is UpdatePermissionRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function UpdatePermissionRequestFromJSON(json: any): UpdatePermissionRequest {
    return UpdatePermissionRequestFromJSONTyped(json, false);
}

export function UpdatePermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function UpdatePermissionRequestToJSON(json: any): UpdatePermissionRequest {
    return UpdatePermissionRequestToJSONTyped(json, false);
}

export function UpdatePermissionRequestToJSONTyped(value?: UpdatePermissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

