/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserListItem } from './UserListItem';
import {
    UserListItemFromJSON,
    UserListItemFromJSONTyped,
    UserListItemToJSON,
    UserListItemToJSONTyped,
} from './UserListItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface UserList
 */
export interface UserList {
    /**
     * 
     * @type {Array<UserListItem>}
     * @memberof UserList
     */
    items: Array<UserListItem>;
    /**
     * 
     * @type {number}
     * @memberof UserList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof UserList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof UserList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the UserList interface.
 */
export function instanceOfUserList(value: object): value is UserList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function UserListFromJSON(json: any): UserList {
    return UserListFromJSONTyped(json, false);
}

export function UserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserListItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function UserListToJSON(json: any): UserList {
    return UserListToJSONTyped(json, false);
}

export function UserListToJSONTyped(value?: UserList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserListItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

