/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetail
 */
export interface UserDetail {
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    betterAuthUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    primaryEmail: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    status: UserDetailStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    statusReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    preferredLocale?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserDetail
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDetail
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDetail
     */
    deactivatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    deactivatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    deactivatedReason?: string | null;
}


/**
 * @export
 */
export const UserDetailStatusEnum = {
    Active: 'active',
    PendingApproval: 'pending_approval',
    Blocked: 'blocked',
    Suspended: 'suspended',
    Deactivated: 'deactivated'
} as const;
export type UserDetailStatusEnum = typeof UserDetailStatusEnum[keyof typeof UserDetailStatusEnum];


/**
 * Check if a given object implements the UserDetail interface.
 */
export function instanceOfUserDetail(value: object): value is UserDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryEmail' in value) || value['primaryEmail'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UserDetailFromJSON(json: any): UserDetail {
    return UserDetailFromJSONTyped(json, false);
}

export function UserDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'betterAuthUserId': json['better_auth_user_id'] == null ? undefined : json['better_auth_user_id'],
        'primaryEmail': json['primary_email'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'status': json['status'],
        'statusReason': json['status_reason'] == null ? undefined : json['status_reason'],
        'preferredLocale': json['preferred_locale'] == null ? undefined : json['preferred_locale'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'deactivatedAt': json['deactivated_at'] == null ? undefined : (new Date(json['deactivated_at'])),
        'deactivatedBy': json['deactivated_by'] == null ? undefined : json['deactivated_by'],
        'deactivatedReason': json['deactivated_reason'] == null ? undefined : json['deactivated_reason'],
    };
}

export function UserDetailToJSON(json: any): UserDetail {
    return UserDetailToJSONTyped(json, false);
}

export function UserDetailToJSONTyped(value?: UserDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'better_auth_user_id': value['betterAuthUserId'],
        'primary_email': value['primaryEmail'],
        'display_name': value['displayName'],
        'status': value['status'],
        'status_reason': value['statusReason'],
        'preferred_locale': value['preferredLocale'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deactivated_at': value['deactivatedAt'] == null ? undefined : ((value['deactivatedAt'] as any).toISOString()),
        'deactivated_by': value['deactivatedBy'],
        'deactivated_reason': value['deactivatedReason'],
    };
}

