/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleAssignmentItem } from './UserRoleAssignmentItem';
import {
    UserRoleAssignmentItemFromJSON,
    UserRoleAssignmentItemFromJSONTyped,
    UserRoleAssignmentItemToJSON,
    UserRoleAssignmentItemToJSONTyped,
} from './UserRoleAssignmentItem';
import type { SortSpec } from './SortSpec';
import {
    SortSpecFromJSON,
    SortSpecFromJSONTyped,
    SortSpecToJSON,
    SortSpecToJSONTyped,
} from './SortSpec';

/**
 * 
 * @export
 * @interface UserRoleAssignmentList
 */
export interface UserRoleAssignmentList {
    /**
     * 
     * @type {Array<UserRoleAssignmentItem>}
     * @memberof UserRoleAssignmentList
     */
    items: Array<UserRoleAssignmentItem>;
    /**
     * 
     * @type {number}
     * @memberof UserRoleAssignmentList
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserRoleAssignmentList
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof UserRoleAssignmentList
     */
    total: number;
    /**
     * 
     * @type {Array<SortSpec>}
     * @memberof UserRoleAssignmentList
     */
    sort?: Array<SortSpec>;
}

/**
 * Check if a given object implements the UserRoleAssignmentList interface.
 */
export function instanceOfUserRoleAssignmentList(value: object): value is UserRoleAssignmentList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function UserRoleAssignmentListFromJSON(json: any): UserRoleAssignmentList {
    return UserRoleAssignmentListFromJSONTyped(json, false);
}

export function UserRoleAssignmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleAssignmentList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserRoleAssignmentItemFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortSpecFromJSON)),
    };
}

export function UserRoleAssignmentListToJSON(json: any): UserRoleAssignmentList {
    return UserRoleAssignmentListToJSONTyped(json, false);
}

export function UserRoleAssignmentListToJSONTyped(value?: UserRoleAssignmentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserRoleAssignmentItemToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortSpecToJSON)),
    };
}

