/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Cookie-session Administrator console API (`/api/administrator`). Authenticate with the Better Auth **session cookie** (send credentials with the request). Every **mutation** also requires an `Origin` (or `Referer`) header matching a trusted origin — the CSRF guard — so a non-browser client must set it explicitly. Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGroupsGroupsInner
 */
export interface UserGroupsGroupsInner {
    /**
     * 
     * @type {string}
     * @memberof UserGroupsGroupsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGroupsGroupsInner
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGroupsGroupsInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof UserGroupsGroupsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the UserGroupsGroupsInner interface.
 */
export function instanceOfUserGroupsGroupsInner(value: object): value is UserGroupsGroupsInner {
    return true;
}

export function UserGroupsGroupsInnerFromJSON(json: any): UserGroupsGroupsInner {
    return UserGroupsGroupsInnerFromJSONTyped(json, false);
}

export function UserGroupsGroupsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupsGroupsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UserGroupsGroupsInnerToJSON(json: any): UserGroupsGroupsInner {
    return UserGroupsGroupsInnerToJSONTyped(json, false);
}

export function UserGroupsGroupsInnerToJSONTyped(value?: UserGroupsGroupsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organizationId'],
        'key': value['key'],
        'name': value['name'],
    };
}

