/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserStatusRequest
 */
export interface UserStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof UserStatusRequest
     */
    action: UserStatusRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof UserStatusRequest
     */
    reason?: string;
}


/**
 * @export
 */
export const UserStatusRequestActionEnum = {
    Approve: 'approve',
    Block: 'block',
    Suspend: 'suspend',
    Reactivate: 'reactivate'
} as const;
export type UserStatusRequestActionEnum = typeof UserStatusRequestActionEnum[keyof typeof UserStatusRequestActionEnum];


/**
 * Check if a given object implements the UserStatusRequest interface.
 */
export function instanceOfUserStatusRequest(value: object): value is UserStatusRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function UserStatusRequestFromJSON(json: any): UserStatusRequest {
    return UserStatusRequestFromJSONTyped(json, false);
}

export function UserStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function UserStatusRequestToJSON(json: any): UserStatusRequest {
    return UserStatusRequestToJSONTyped(json, false);
}

export function UserStatusRequestToJSONTyped(value?: UserStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'reason': value['reason'],
    };
}

