/* tslint:disable */
/* eslint-disable */
/**
 * DevResponse Administrator API
 * Administrator console API (`/api/administrator`). Authenticate EITHER with the Better Auth **session cookie** (send credentials with the request; every **mutation** then also requires an `Origin` or `Referer` header matching a trusted origin — the CSRF guard — which a browser sets itself and a server-side caller must add) OR with a **bearer** API key / JWT, whose effective authority is the intersection of its scopes and the permissions of its owner and which is exempt from the origin guard. The one exception is `DELETE /users/{id}/impersonate`, which bypasses the permission guard by design and is therefore **cookie-session only** (see that operation). Org admins are scoped to their own organization (out-of-scope resources return 404, not 403). Errors use `{ error, message, requestId }`; every response carries an `x-request-id` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRoleAssignmentItem
 */
export interface UserRoleAssignmentItem {
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    roleId: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    roleKey: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    roleName: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    roleDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    organizationSlug?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRoleAssignmentItem
     */
    organizationName?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserRoleAssignmentItem
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the UserRoleAssignmentItem interface.
 */
export function instanceOfUserRoleAssignmentItem(value: object): value is UserRoleAssignmentItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('roleKey' in value) || value['roleKey'] === undefined) return false;
    if (!('roleName' in value) || value['roleName'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UserRoleAssignmentItemFromJSON(json: any): UserRoleAssignmentItem {
    return UserRoleAssignmentItemFromJSONTyped(json, false);
}

export function UserRoleAssignmentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleAssignmentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roleId': json['role_id'],
        'roleKey': json['role_key'],
        'roleName': json['role_name'],
        'roleDescription': json['role_description'] == null ? undefined : json['role_description'],
        'organizationId': json['organization_id'],
        'organizationSlug': json['organization_slug'] == null ? undefined : json['organization_slug'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function UserRoleAssignmentItemToJSON(json: any): UserRoleAssignmentItem {
    return UserRoleAssignmentItemToJSONTyped(json, false);
}

export function UserRoleAssignmentItemToJSONTyped(value?: UserRoleAssignmentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role_id': value['roleId'],
        'role_key': value['roleKey'],
        'role_name': value['roleName'],
        'role_description': value['roleDescription'],
        'organization_id': value['organizationId'],
        'organization_slug': value['organizationSlug'],
        'organization_name': value['organizationName'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

