/**
 * Email template catalog + renderer (specs.md §35).
 *
 * Templates live in `app_email_templates` and are editable through the
 * administrator Email workspace. This module holds the code-level
 * DEFAULTS — the renderer falls back to these when a (key, locale) row
 * is missing, so a deleted or never-seeded row can never break a flow.
 *
 * Kept free of `server-only` and runtime imports (like
 * `src/lib/admin/permissions.ts`) so the seed script and unit tests can
 * import it under plain Node.
 */

export interface EmailTemplateDefinition {
  key: string;
  subject: string;
  bodyHtml: string;
  bodyText: string;
  description: string;
  /** Variable names the template understands, for the editor UI. */
  variables: ReadonlyArray<string>;
}

/**
 * Built-in defaults. Keep in sync with the seeds in migration
 * `0006-email-outbox-and-templates.sql`.
 */
export const DEFAULT_EMAIL_TEMPLATES: ReadonlyArray<EmailTemplateDefinition> = [
  {
    key: "password_reset",
    subject: "Reset your password",
    bodyHtml:
      "<p>Hi {{name}},</p>" +
      "<p>We received a request to reset your password. Click the link below to choose a new one. This link expires shortly.</p>" +
      '<p><a href="{{resetUrl}}">Reset your password</a></p>' +
      "<p>If you did not request this, you can safely ignore this email.</p>",
    bodyText:
      "Hi {{name}},\n\n" +
      "We received a request to reset your password. Open the link below to choose a new one. This link expires shortly.\n\n" +
      "{{resetUrl}}\n\n" +
      "If you did not request this, you can safely ignore this email.",
    description:
      'Sent for the forgot-password flow and the administrator "send reset email" action.',
    variables: ["name", "resetUrl"],
  },
  {
    key: "test_email",
    subject: "Test email from {{appName}}",
    bodyHtml:
      "<p>This is a test email sent from the {{appName}} administrator Email workspace by {{sentBy}}.</p>" +
      "<p>If you can read this, outbound email delivery is working.</p>",
    bodyText:
      "This is a test email sent from the {{appName}} administrator Email workspace by {{sentBy}}.\n\n" +
      "If you can read this, outbound email delivery is working.",
    description: 'Sent by the administrator "send test email" action.',
    variables: ["appName", "sentBy"],
  },
] as const;

export type EmailTemplateKey = "password_reset" | "test_email";

export function getDefaultEmailTemplate(key: string): EmailTemplateDefinition | undefined {
  return DEFAULT_EMAIL_TEMPLATES.find((t) => t.key === key);
}

/** Minimal HTML entity escape for variable VALUES interpolated into HTML bodies. */
export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/**
 * Substitutes `{{variable}}` placeholders.
 *
 * Security contract:
 *   - In `html` mode every variable VALUE is entity-escaped, so user-
 *     controlled values (display names, emails) can never inject markup
 *     into a template. Reset URLs are generated by Better Auth, not by
 *     users, and survive escaping intact inside `href="..."`.
 *   - Unknown placeholders are left verbatim so an admin editing a
 *     template sees `{{typo}}` in the outbox instead of silent loss.
 */
export function renderEmailTemplate(
  template: string,
  variables: Record<string, string>,
  mode: "html" | "text",
): string {
  return template.replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, (placeholder, name: string) => {
    const value = variables[name];
    if (value === undefined) return placeholder;
    return mode === "html" ? escapeHtml(value) : value;
  });
}
